# ==== 데이터 입력 공간 ====
# 사용할 때는 { 1: ("단어", "뜻"), 2: ("단어", "뜻") } 형태로 채우면 됩니다.
page_1 = {
    1: ("meet", "v. 충족시키다"),
    2: ("numerous", "a. 많은"),
    3: ("describe", "v. 묘사하다"),
    4: ("talkative", "a. 수다스러운"),
    5: ("clear", "a. 명백한"),
    6: ("flavor", "n. 맛 v. 맛을 내다"),
    7: ("taste", "n. 맛, 취향"),
    8: ("hesitantly", "ad. 머뭇거리며"),
    9: ("yearly", "a. 매년의 ad. 매년"),
    10: ("annual", "a. 연례의"),
    11: ("monthly", "a. 월간의 ad. 달마다"),
    12: ("marketing", "n. 마케팅, 매매"),
    13: ("hourly", "a. 매시간의 ad. 매시간마다"),
    14: ("exceptional", "a. 뛰어난, 보통이 아닌"),
    15: ("highly", "ad. 매우, 대단히"),
    16: ("daily", "a. 매일의 ad. 날마다"),
    17: ("acquire", "v. 인수하다, 획득하다"),
    18: ("weekly", "a. 매주의 ad. 매주마다"),
    19: ("sale", "n. 판매"),
    20: ("fascinating", "a. 매혹적인"),
    21: ("overhead", "a. 머리 위의 ad. 머리위에"),
    22: ("feed", "v. 먹이다, n. 사육"),
    23: ("closely", "ad. 면밀하게, 친밀하게"),
    24: ("duty-free", "a. 면세의, 세금없는"),
    25: ("immunization", "n. 면역, 예방주사"),
    26: ("immunize", "v. 면역을 주다"),
    27: ("immune", "a. 면역성의"),
    28: ("interviewee", "n. 인터뷰대상자"),
    29: ("interviewer", "n. 면접관"),
    30: ("exempt", "v. 면제하다 a. 면제된"),
    31: ("extinction", "n. 소멸, 전멸"),
    32: ("endangered", "a. 멸종위기에 처한"),
    33: ("celebrity", "n. 명성, 유명인"),
    34: ("reputation", "n. 명성, 평판"),
    35: ("specification", "n. 열거, 사양서, 설명서"),
    36: ("statement", "n. 진술, 성명서"),
    37: ("honorary", "a. 명예직의"),
    38: ("nominal", "a. 이름의, 명의상의"),
    39: ("business card", "n. 명함"),
    40: ("specifically", "ad. 명확하게, 말하자면"),
    41: ("clearly", "ad. 명백하게"),
    42: ("wakeup call", "n. 모닝콜"),
    43: ("replication", "n. 응답, 모사, 복사"),
    44: ("gather", "v. 모으다"),
    45: ("venture", "n. 모험 v. 위험을무릅쓰다"),
    46: ("vague", "a. 막연한, 모호한"),
    47: ("objective", "n. 목표 a. 객관적인"),
    48: ("purpose", "n. 목적 v. 의도하다"),
    49: ("aim", "n. 목표 v. 목표로 삼다"),
    50: ("share", "n. 몫 v. 분배하다"),
    51: ("weigh", "v. 무게를 달다"),
    52: ("heavily", "ad. 심하게, 크게"),
    53: ("weight", "n. 무게"),
    54: ("incompetent", "a. 무능한, 쓸모없는 n. 무능력자"),
    55: ("complimentary", "a. 무료의, 칭찬하는"),
    56: ("countless", "a. 무수한, 셀 수없는"),
    57: ("embargo", "n. 보도금지 v. 출항을금지하다"),
    58: ("annulment", "n. 취소, 폐지, 무효"),
    59: ("matter", "v. 중요하다, n. 문제"),
    60: ("inflation", "n. 폭등, 물가상승"),
    61: ("beat", "v. 치다, 이기다 n. 박동"),
    62: ("outstanding", "a. 뛰어난, 눈에띄는"),
    63: ("prospective", "a. 가망이 있는, 장래의"),
    64: ("ahead", "ad. 앞으로"),
    65: ("delicate", "a. 섬세한"),
    66: ("push", "v. 밀다, 밀치다"),
    67: ("densely", "ad. 빽빽이, 촘촘히"),
    68: ("alter", "v. 바꾸다"),
    69: ("vary", "v. 달라지다, 바꾸다"),
    70: ("mop", "v. 바닥을 닦다"),
    71: ("shore", "n. 바닷가, 해안"),
    72: ("desirable", "a. 바람직한"),
    73: ("advisable", "a. 권장할만한"),
    74: ("escort", "v. 바래다주다"),
    75: ("correctly", "ad. 바르게"),
    76: ("applaud", "v. 박수갈채를 보내다"),
    77: ("deprivation", "n. 박탈"),
    78: ("opposition", "n. 반대"),
    79: ("contrary", "a. 반대의"),
    80: ("reverse", "v. 반대로 하다"),
    81: ("opponent", "a. 반대하는 n. 반대자"),
    82: ("object", "n. 물체 v. 반대하다"),
    83: ("imperative", "a. 절대적으로 필요한"),
    84: ("necessarily", "ad. 반드시"),
    85: ("refute", "v. 반박하다"),
    86: ("double check", "v. 반복확인하다, 재확인하다"),
    87: ("repeatedly", "ad. 반복하여, 몇번이고"),
    88: ("reflection", "n. 반사"),
    89: ("reflective", "a. 반사하는, 반영하는"),
    90: ("reaction", "n. 반응"),
    91: ("insubordinate", "a. 반항하는 n. 반항자"),
    92: ("return", "n. 반환"),
    93: ("acceptably", "ad. 받아들일 수 있게"),
    94: ("ticketing", "n. 발권"),
    95: ("improvement", "n. 개선"),
    96: ("develop", "n. 발전시키다, 개발하다"),
    97: ("presentation", "n. 발표"),
    98: ("announce", "n. 발표하다"),
    99: ("reveal", "v. 드러내다, 밝히다"),
    100: ("stander-by", "n. 방관자, 구경꾼"),
    101: ("method", "n. 방법"),
    102: ("soundproof", "a. 방음의 v. 방음장치를 하다"),
    103: ("emission", "n. 방출, 발산"),
    104: ("discharge", "v. 방출하다, 짐을 내리다"),
    105: ("interruption", "n. 방해"),
    106: ("deterrent", "a. 방해하는 n. 방해물"),
    107: ("disturbing", "a. 방해하는, 교란시키는"),
    108: ("impede", "v. 방해하다"),
}
page_2 = {
    109: ("interfere", "v. 방해하다, 간섭하다"),
    110: ("disturb", "v. 방해하다"),
    111: ("distributor", "n. 배급, 유통업자, 업체"),
    112: ("delivery", "n. 배달, 연설"),
    113: ("deliver", "n. 배달하다, 연설하다"),
    114: ("ship", "n. 발송하다, 수송하다"),
    115: ("allocation", "n. 배당, 할당"),
    116: ("dividend", "n. 배당, 배당금"),
    117: ("arrange", "v. 배열하다, 준비하다"),
    118: ("assign", "v. 할당하다"),
    119: ("distribute", "v. 배포하다, 뿌리다"),
    120: ("percentage", "n. 백분율, 비율"),
    121: ("translation", "n. 번역"),
    122: ("prosperity", "n. 번영, 번창, 성공"),
    123: ("thrive", "v. 번창하다, 번영하다"),
    124: ("flourish", "v. 번영하다, 잘 자라다"),
    125: ("fine", "n. 벌금 a. 괜찮은"),
    126: ("earn", "v. 벌다, 얻다"),
    127: ("ordinance", "n. 법령, 조례"),
    128: ("legislation", "n. 법률제정, 입법"),
    129: ("closet", "n. 벽장"),
    130: ("transform", "v. 변형시키다"),
    131: ("reimbursement", "v. 변제, 상환"),
    132: ("attorney", "n. 변호사, 대리인"),
    133: ("annex", "v. 부가하다, n. 부록"),
    134: ("illness", "n. 병, 질병"),
    135: ("ailing", "a. 병든, 병약한"),
    136: ("claim check", "n. 번호표, 보관증"),
    137: ("apparently", "ad. 명백히"),
    138: ("transfer", "v. 옮기다, 전송시키다 n. 이동, 전송"),
    139: ("retaliation", "n. 보복, 앙갚음"),
    140: ("coverage", "n. 적용범위, (뉴스)보도"),
    141: ("jewelry", "n. 보석류"),
    142: ("complement", "n. 보충물 v. 보완하다"),
    143: ("supplement", "n. 보충, 추가 v. 보충하다"),
    144: ("retain", "v. 보유하다"),
    145: ("guarantee", "v. 보장하다"),
    146: ("grant", "v. 부여하다 n. 보조금"),
    147: ("assistant", "n. 보조, 보조의"),
    148: ("conserve", "v. 보존하다, 보호하다"),
    149: ("maintain", "v. 유지하다, 지속하다"),
    150: ("endorse", "v. (어음,수표)배서, 서명하다"),
    151: ("warranty", "n. 보증, 보증서"),
    152: ("ensure", "v. 보장하다"),
    153: ("usually", "ad. 보통, 일반적으로"),
    154: ("pedestrian", "n. 보행자"),
    155: ("insurance", "n. 보험"),
    156: ("premium", "n. 보험료"),
    157: ("protective", "a. 보호하는"),
    158: ("protect", "v. 보호하다"),
    159: ("restore", "v. 복구하다"),
    160: ("raffle", "v. 제비뽑기하다 n. 복권판매"),
    161: ("copy", "v. 복사하다 n. 책한권, 복사물"),
    162: ("copier", "n. 복사기"),
    163: ("complicate", "v. 복잡하게 만들다"),
    164: ("headquarters", "n. 본사"),
    165: ("inherently", "ad. 선천적으로"),
    166: ("plenary session", "n. 본회의, 전체회의"),
    167: ("envelope", "n. 봉투"),
    168: ("additional", "a. 추가적인"),
    169: ("emerge", "v. 나오다, 드러나다"),
    170: ("impose", "n. 부과하다"),
    171: ("bookkeeping", "n. 부기(기록)"),
    172: ("responsibility", "n. 책임, 임무"),
    173: ("bounce", "v. 튀다, 튀어오르다"),
    174: ("real estate agent", "n. 부동산중개인"),
    175: ("dock", "n. 부두, 선창"),
    176: ("enviable", "a. 부러운, 선망의대상인"),
    177: ("proportion", "n. 비율"),
    178: ("partial", "a. 부분적인"),
    179: ("division", "n. 분배, 부서"),
    180: ("incidental", "a. 우발적인, 일어나기쉬운"),
    181: ("corrosion", "n. 부식"),
    182: ("boost", "v. 부흥시키다, 밀어올리다"),
    183: ("improperly", "ad. 부적절하게"),
    184: ("improper", "a. 부적절한"),
    185: ("inaccurate", "a. 부정확한, 잘못된"),
    186: ("incorrect", "a. 부정확한, 응답답지않은"),
    187: ("deficient", "a. 부족한, 불충분한"),
    188: ("carelessly", "ad. 부주의하게, 경솔하게"),
    189: ("perishable", "a. 썩기 쉬운"),
    190: ("subordinate", "a. 하위의, 아래의"),
    191: ("evident", "a. 분명한, 명백한"),
    192: ("evidently", "ad. 분명하게"),
    193: ("analysis", "n. 분석"),
    194: ("atmosphere", "n. 분위기, 공기"),
    195: ("dispute", "v. 논쟁하다"),
    196: ("unable", "a. 할 수없는"),
    197: ("inevitable", "a. 불가피한"),
    198: ("unfairly", "ad. 불공평하게"),
    199: ("unstable", "a. 불안정한"),
    200: ("insecure", "a. 불안전한, 위험에 처한"),
    201: ("contingency", "n. 우연, 우발적사건"),
    202: ("inconsistency", "n. 불일치, 모순"),
    203: ("inconvenience", "n. 불편함"),
    204: ("complaint", "n. 불평"),
    205: ("complain", "v. 불평하다"),
    206: ("unfortunately", "ad. 불행하게도"),
    207: ("uncertain", "a. 불명확한"),
    208: ("depression", "n. 불경기"),
    209: ("pour", "v. 액체를 따르다, 붓다"),
    210: ("collapse", "n. 붕괴 v. 무너지다"),
    211: ("affix", "v. 첨부하다, 붙이다 n. 접사"),
    212: ("attach", "v. 붙이다, 첨부하다"),
    213: ("tip", "n. 조언 v. 붙이다"),
    214: ("comparison", "n. 비교, 대조"),
    215: ("comparable", "a. 비교할만한"),
    216: ("relatively", "ad. 비교적"),
}
page_3 = {
    217: ("compare", "v. 비교하다"),
    218: ("secretary", "n. 비서"),
    219: ("blank", "a. 빈칸의 n. 공백"),
    220: ("expense", "n. 비용"),
    221: ("empty", "a. 텅 빈"),
    222: ("ratio", "n. 비율"),
    223: ("unusually", "ad. 평소와는 달리"),
    224: ("critical", "a. 비판적인, 결정적인"),
    225: ("criticize", "v. 비평하다"),
    226: ("aircraft", "n. 비행기, 선체"),
    227: ("meagerly", "a. 빈약하게, 불충분하게"),
    228: ("lend", "v. 빌려주다"),
    229: ("deviate", "v. 벗어나다, 빗나가다"),
    230: ("owe", "v. 빚지다"),
    231: ("fast", "a. 빠른 ad. 빠르게"),
    232: ("rapid", "a. 빠른"),
    233: ("quickly", "ad. 빠르게"),
    234: ("apologize", "v. 사과하다"),
    235: ("fraud", "n. 사기, 부정행위"),
    236: ("morale", "n. 사기, 의욕"),
    237: ("ladder", "n. 사다리"),
    238: ("missing", "a. 사라진"),
    239: ("lovely", "a. 사랑스러운"),
    240: ("duplicate", "n. 사본 a. 중복의"),
    241: ("actually", "ad. 사실"),
    242: ("entrepreneur", "n. 사업가, 기업가"),
    243: ("user-friendly", "a. 사용하기 쉬운"),
    244: ("unused", "a. 사용하지 않는"),
    245: ("resignation", "n. 사임, 사직"),
    246: ("photograph", "n. 사진"),
    247: ("luxurious", "a. 사치스러운"),
    248: ("cutback", "n. 삭감, 축소"),
    249: ("insert", "v. 삽입하다"),
    250: ("award", "n. 상"),
    251: ("remind", "v. 상기시키다, 생각케하다"),
    252: ("substantial", "a. 상당한"),
    253: ("significant", "a. 상당한"),
    254: ("fairly", "ad. 공평하게"),
    255: ("significantly", "ad. 상당히"),
    256: ("envision", "v. 상상하다, 구상하다"),
    257: ("elaborate", "v. 공들여 만들다"),
    258: ("detailed", "a. 자세한"),
    259: ("offset", "v. 상쇄하다"),
    260: ("showing", "n. 전시, 진열"),
    261: ("equivalent", "a. 상응하는"),
    262: ("trade show", "n. 무역박람회"),
    263: ("merchandise", "n. 상품"),
    264: ("commodity", "n. 생필품"),
    265: ("voucher", "n. 상품권"),
    266: ("interact", "v. 상호작용하다"),
    267: ("reciprocal", "a. 상호의, 답례의"),
    268: ("reimburse", "v. 상환하다, 배상하다"),
    269: ("redeemable", "a. 상환할 수 있는"),
    270: ("leak", "n. 누수 v. 새어나오다"),
    271: ("pitfall", "n. 예상치 못한 위험"),
    272: ("production", "n. 생산, 생산량"),
    273: ("productive", "a. 생산적인"),
    274: ("product", "n. 생산품"),
    275: ("produce", "v. 생산하다 n. 농산물"),
    276: ("live", "v. 살다, 살아남다, 생방으로"),
    277: ("premises", "n. 사유지, 부지, 구내"),
    278: ("rush", "v. 서두르다 n. 돌진"),
    279: ("each other", "(문장맨뒤) 서로서로"),
    280: ("document", "n. 서류"),
    281: ("briefcase", "n. 서류가방"),
    282: ("preamble", "n. 서문, 머리말"),
    283: ("service", "n. 서비스, 봉사"),
    284: ("shelf", "n. 선반"),
    285: ("declare", "n. 선언하다"),
    286: ("unbiased", "a. 선입견이 없는, 편견없는"),
    287: ("shipment", "n. 선적, 발송, 출고"),
    288: ("choice", "n. 선정, 선택"),
    289: ("selection", "n. 선택"),
    290: ("fan", "n. 선풍기 v. 불어주다"),
    291: ("preferred", "a. 우대하는"),
    292: ("design", "n. 디자인 v. 디자인을 하다"),
    293: ("persuasive", "a. 설득력있는"),
    294: ("institution", "n. 기관, 시설"),
    295: ("establish", "v. 설립하다"),
    296: ("description", "n. 묘사"),
    297: ("illustrate", "v. 설명하다, 삽화를 넣다"),
    298: ("survey", "n. 설문조사"),
    299: ("fixture", "n. 설비, 시설물"),
    300: ("install", "v. 설치하다"),
    301: ("success", "n. 성공"),
    302: ("successfully", "ad. 성공적으로, 운좋게"),
    303: ("succeed", "v. 성공하다, 출세하다"),
    304: ("maturity", "n. 성숙, 숙성"),
    305: ("growth", "n. 성장"),
    306: ("grow", "v. 성장하다"),
    307: ("accomplish", "v. 성취하다"),
    308: ("customs", "n. 세관"),
    309: ("tax", "n. 세금"),
    310: ("force", "n. 힘 v. 강제로 시키다"),
    311: ("sleek", "a. 매끄러운"),
    312: ("scrutinize", "v. 자세히 조사하다"),
    313: ("laundry", "n. 세탁물"),
    314: ("introduce", "v. 소개하다, 도입하다"),
    315: ("shower", "n. 소나기 v. 샤워를 하다"),
    316: ("retail", "a. 소매의 ad. 소매로"),
    317: ("consumer", "n. 소비자"),
    318: ("litigation", "n. 소송"),
    319: ("proprietor", "n. 소유자, 경영자"),
    320: ("belongings", "n. 소지품"),
    321: ("assembly", "n. 조립, 집회"),
    322: ("booklet", "n. 안내책자"),
    323: ("brochure", "n. 안내책자"),
    324: ("manual", "n. 설명서"),
}
page_4 = {
    325: ("socket", "n. 콘센트"),
    326: ("downsize", "v. 크기를 줄이다"),
    327: ("wrist watch", "n. 손목시계"),
    328: ("damaged", "a. 손상된"),
    329: ("seniority", "n. 선임, 연공서열 a. 선임의"),
    330: ("damage", "n. 손해 v. 손해를 입히다"),
    331: ("candid", "a. 솔직한, 직설한"),
    332: ("remittance", "n. 송금액, 송금"),
    333: ("invoice", "n. 송장, 청구서"),
    334: ("means", "n. 수단, 방법"),
    335: ("accept", "v. 수용하다, 받아들이다"),
    336: ("renovation", "n. 수선, 수리"),
    337: ("repair", "v. 수리하다"),
    338: ("fix", "v. 고치다, 고정시키다"),
    339: ("entail", "v. 수반하다, 결과를남기다"),
    340: ("fee", "n. 수수료"),
    341: ("recipient", "n. 수령인, 수상자"),
    342: ("tuition fee", "n. 수업료"),
    343: ("capacity", "n. 수용량"),
    344: ("lucrative", "a. 수지맞는, 돈이되는"),
    345: ("revenue", "n. 수익"),
    346: ("revision", "n. 수정, 개정"),
    347: ("modification", "n. 수정"),
    348: ("amend", "v. 수정하다"),
    349: ("revise", "v. 수정하다, 개정하다"),
    350: ("modify", "v. 수정하다"),
    351: ("handmade", "a. 손으로 만든"),
    352: ("aquarium", "n. 수족관"),
    353: ("collection", "n. 수집"),
    354: ("baggage", "n. 수하물"),
    355: ("conduct", "v. 수행하다, 실시하다"),
    356: ("circulation", "n. 순환"),
    357: ("easy", "a. 수월한"),
    358: ("easily", "ad. 쉽게, 단연코, 확실히"),
    359: ("suite", "n. 스위트룸, 세트"),
    360: ("habit", "n. 습관"),
    361: ("customary", "a. 습관적인, 관습적인"),
    362: ("passenger", "n. 승객"),
    363: ("crew", "n. 승무원"),
    364: ("approval", "n. 승인, 허가"),
    365: ("approve", "v. 승인하다"),
    366: ("promotion", "n. 승진, 홍보"),
    367: ("promote", "v. 승진시키다, 장려하다"),
    368: ("session", "n. 수업, 회의, 기간"),
    369: ("early", "a. 초기의 ad. 초기부터"),
    370: ("countryside", "n. 시골"),
    371: ("rural", "a. 시골의"),
    372: ("timely", "a. 시의적절한"),
    373: ("stream", "n. 개울, 흐름"),
    374: ("obsolete", "a. 쓸모없게된, 시대에 뒤처진"),
    375: ("attempt", "n. 시도 v. 시도하다"),
    376: ("facility", "n. 시설, 설비"),
    377: ("test drive", "n. 시운전"),
    378: ("commence", "v. 시작하다"),
    379: ("initiate", "v. 시작하다"),
    380: ("market share", "n. 시장점유율"),
    381: ("jet lag", "n. 시차증"),
    382: ("trial and error", "n. 시행착오"),
    383: ("enforce", "v. 시행하다"),
    384: ("cafeteria", "n. 구내식당"),
    385: ("grocery store", "n. 식료품점"),
    386: ("vegetable", "n. 야채"),
    387: ("diet", "n. 식이요법"),
    388: ("identification", "n. 신원확인"),
    389: ("freshness", "n. 신선함"),
    390: ("prompt", "a. 신속한"),
    391: ("quick", "a. 빠른"),
    392: ("expedite", "v. 신속히 처리하다"),
    393: ("reliable", "a. 믿을수있는"),
    394: ("application", "n. 신청서, 지원서"),
    395: ("indoors", "ad. 실내에서, 실내로"),
    396: ("disappointment", "n. 실망"),
    397: ("disappointing", "a. 실망시키는"),
    398: ("performance", "n. 실적, 수행, 공연"),
    399: ("realistic", "a. 현실적인"),
    400: ("feasible", "a. 실행가능한, 있을법한"),
    401: ("practice", "n. 연습, 관행, 개업지"),
    402: ("execute", "v. 실행하다, 실시하다"),
    403: ("implement", "v. 실시하다, 실행하다 n. 이행"),
    404: ("laboratory", "n. 실험실"),
    405: ("experiment", "n. 실험"),
    406: ("severely", "ad. 심하게"),
    407: ("bilateral", "a. 양쪽의, 쌍방의"),
    408: ("pile", "n. 더미 v. 쌓아올리다"),
    409: ("waste", "n. 쓰레기 v. 낭비하다"),
    410: ("possible", "a. 가능한, 할수있는"),
    411: ("presumably", "ad. 아마도, 짐작컨데"),
    412: ("deteriorate", "v. 악화시키다"),
    413: ("aggravate", "v. 악화시키다"),
    414: ("safety", "n. 안전"),
    415: ("stability", "n. 안정성"),
    416: ("aware", "a. 인지하는, 알고 있는"),
    417: ("conscious", "a. 의식하고있는, 알고 있는"),
    418: ("inform", "v. 알리다, 통지하다"),
    419: ("notice", "v. 알리다"),
    420: ("pressure", "n. 압력"),
    421: ("confiscate", "v. 압수하다"),
    422: ("forward", "ad. 앞으로, 전방으로"),
    423: ("accessory", "n. 부대용품"),
    424: ("amount", "n. 양, 총액"),
    425: ("trigger", "n. 방아쇠 v. 촉발시키다"),
    426: ("pill", "n. 알약"),
    427: ("slightly", "ad. 약간, 조금"),
    428: ("marginal", "a. 미미한, 중요하지않은"),
    429: ("pharmacy", "n. 약국"),
    430: ("medication", "n. 약, 약물치료"),
    431: ("pharmacist", "n. 약사"),
    432: ("medicinal", "a. 약효 있는"),
}
page_5 = {
    433: ("slice", "n. 부분,조각 v. 조각을내다"),
    434: ("quantity", "n. 수량"),
    435: ("transferable", "a. 양도할 수 있는"),
    436: ("curd", "n. 굳어진 것"),
    437: ("cite", "v. 인용하다, 열거하다"),
    438: ("mention", "v. 언급하다"),
    439: ("obtain", "v. 얻다"),
    440: ("rigid", "a. 단단한, 고정된, 엄격한"),
    441: ("rigorously", "ad. 엄격하게, 혹독하게"),
    442: ("strictly", "ad. 엄격히"),
    443: ("stringently", "ad. 가혹하게"),
    444: ("tremendous", "a. 엄청난"),
    445: ("passenger ferry", "n. 여객선"),
    446: ("assorted", "a. 여러가지의, 갖가지의"),
    447: ("consensus", "n. 합의, 일치, 여론"),
    448: ("remain", "v. 남다, 남아있다"),
    449: ("tour", "n. 여행 v. 견학하다"),
    450: ("travel agency", "n. 여행사"),
    451: ("itinerary", "n. 여행일정"),
    452: ("adversity", "n. 역경, 불운"),
    453: ("connection", "n. 연결"),
    454: ("associate", "n. 직원, 동료, 연합"),
    455: ("study", "n. 연구 v. 검토하다"),
    456: ("research", "n. 연구 v. 조사하다"),
    457: ("institute", "n. 협회 v. 설립하다"),
    458: ("pension", "n. 연금"),
    459: ("delay", "v. 연기하다, 미루다"),
    460: ("defer", "v. 연기하다, 유예하다"),
    461: ("podium", "n. 연단, 강의단상"),
    462: ("chronological", "a. 연대순의, 시간순의"),
    463: ("fuel", "n. 연료"),
    464: ("continuation", "n. 유예, 연속, 지속"),
    465: ("continuity", "n. 연속성"),
    466: ("consecutive", "a. 연속적인, 잇따른"),
    467: ("extension", "n. 연장"),
    468: ("extended", "a. 연장된"),
    469: ("conjunction", "n. 연결, 결합, 접속사"),
    470: ("banquet", "n. 연회"),
    471: ("function", "n. 기능, 작동"),
    472: ("enthusiastically", "ad. 열광적으로"),
    473: ("hard", "a. 어려운 ad. 열심히"),
    474: ("enthusiasm", "n. 열중"),
    475: ("apprehensive", "a. 염려하는"),
    476: ("concerned", "a. 염려하는, 걱정하는"),
    477: ("inspiration", "n. 영감"),
    478: ("permanent", "a. 영구적인"),
    479: ("receipt", "n. 영수증, 수령"),
    480: ("nutrition", "n. 영양"),
    481: ("permanently", "ad. 영구적으로"),
    482: ("implication", "n. 암시"),
    483: ("impact", "n. 영향 v. 충격을주다"),
    484: ("effect", "n. 영향, 효과"),
    485: ("clout", "n. 영향력 v. 강타하다"),
    486: ("susceptible", "a. 예민한, 민감한"),
    487: ("influence", "n. 영향 v. 영향을주다"),
    488: ("foresee", "v. 예견하다, 미리보다"),
    489: ("foreseeable", "a. 예측할 수 있는"),
    490: ("unexpected", "a. 예기치않은, 예상치못한"),
    491: ("prevention", "n. 예방, 방지"),
    492: ("precaution", "n. 예방책"),
    493: ("budget", "n. 예산"),
    494: ("expectation", "n. 예상, 기대"),
    495: ("projection", "n. 예상"),
    496: ("expect", "v. 기대하다"),
    497: ("reservation", "n. 예약"),
    498: ("reserved", "a. 예약된"),
    499: ("book", "v. 예약하다"),
    500: ("reserve", "v. 예약하다"),
    501: ("exception", "n. 예외"),
    502: ("exceptionally", "ad. 이례적으로"),
    503: ("courtesy", "n. 예의"),
    504: ("politely", "ad. 예의바르게"),
    505: ("courteous", "a. 정중한"),
    506: ("predict", "v. 예측하다"),
    507: ("rise", "v. 오르다 n. 증가"),
    508: ("pollutant", "n. 오염물질"),
    509: ("contaminate", "v. 오염시키다"),
    510: ("temperature", "n. 온도"),
    511: ("raise", "v. 올리다"),
    512: ("suitcase", "n. 출장가방"),
    513: ("advocate", "n. 변호사, 대리인"),
    514: ("complete", "a. 완전한 v. 작성하다"),
    515: ("finished", "a. 완성된"),
    516: ("absolute", "a. 절대적인"),
    517: ("absolutely", "ad. 절대적으로"),
    518: ("entirely", "ad. 완전히"),
    519: ("completely", "ad. 완벽하게"),
    520: ("relieve", "v. 완화시키다"),
    521: ("alleviate", "v. 완화시키다"),
    522: ("round trip", "n. 왕복여행"),
    523: ("appearance", "n. 외관, 외모"),
    524: ("foreign currency", "n. 외화 (외국통화)"),
    525: ("demanding", "a. 까다로운"),
    526: ("cater", "v. 음식을 공급하다"),
    527: ("require", "v. 요구하다"),
    528: ("demand", "v. 요구하다"),
    529: ("request", "v. 요청하다"),
    530: ("rate", "n. 비율"),
    531: ("charge", "n. 요금 v. 청구하다"),
    532: ("fluctuate", "v. 오르내리다"),
    533: ("cuisine", "n. 요리"),
    534: ("recipe", "n. 요리법"),
    535: ("ingredient", "n. 재료"),
    536: ("factor", "n. 요인"),
    537: ("summarize", "v. 요약하다"),
    538: ("condense", "v. 압축하다"),
    539: ("abbreviate", "v. 생략하다 a. 생략한"),
    540: ("solicit", "v. 간청하다, 부탁하다"),
}
page_6 = {
    541: ("encouraging", "a. 유망한"),
    542: ("attire", "n. 의복"),
    543: ("facilitate", "v. 용이하게 하다, 촉진하다"),
    544: ("elegant", "a. 우아한"),
    545: ("accidentally", "ad. 우연히"),
    546: ("postage", "n. 우편요금"),
    547: ("favorably", "ad. 우호적으로"),
    548: ("cultivation", "n. 양식, 경작"),
    549: ("detour", "v. 우회하다, 돌아가다"),
    550: ("divert", "v. 우회하다, 전환하다"),
    551: ("athlete", "n. 운동선수"),
    552: ("transportation", "n. 교통"),
    553: ("drivers license", "n. 운전면허증"),
    554: ("work station", "n. 일터, 사무실"),
    555: ("originally", "ad. 원래는"),
    556: ("horticulture", "n. 원예농업"),
    557: ("aid", "v. 원조하다, 돕다"),
    558: ("superior", "a. 우수한"),
    559: ("close call", "n. 위기일발, 구사일생"),
    560: ("violation", "n. 위반"),
    561: ("violate", "v. 위반하다"),
    562: ("infringe", "v. 위반하다"),
    563: ("committee", "n. 위원회"),
    564: ("poison", "n. 독"),
    565: ("consignment", "n. 위탁, 배송"),
    566: ("jeopardize", "v. 위태롭게 하다"),
    567: ("hazard", "n. 위험"),
    568: ("hazardous", "a. 위험한"),
    569: ("regrettable", "a. 유감스러운"),
    570: ("regrettably", "ad. 유감스럽게"),
    571: ("promising", "a. 유망한"),
    572: ("famous", "a. 유명한"),
    573: ("renowned", "a. 유명한"),
    574: ("induce", "v. 유도하다"),
    575: ("legacy", "n. 유산"),
    576: ("flexibly", "ad. 유연하게"),
    577: ("beneficial", "a. 유익한"),
    578: ("informative", "a. 유익한, 도움이 되는"),
    579: ("site", "n. 위치, 현장"),
    580: ("maintenance", "n. 유지, 관리"),
    581: ("form", "n. 외형 v. 형성하다"),
    582: ("valid", "a. 유효한"),
    583: ("foster", "v. 양육하다"),
    584: ("outline", "n. 윤곽 v. 개요를 그리다"),
    585: ("flexibility", "n. 유연성"),
    586: ("premier", "a. 최고의"),
    587: ("retirement", "n. 은퇴"),
    588: ("retire", "v. 은퇴하다"),
    589: ("beverage", "n. 음료"),
    590: ("respondent", "n. 응답자"),
    591: ("respond", "v. 응답하다"),
    592: ("feedback", "n. 의견"),
    593: ("clothing", "n. 의복, 옷"),
    594: ("apparel", "n. 의복, 옷"),
    595: ("duty", "n. 의무"),
    596: ("compulsory", "a. 의무적인, 강제적인"),
    597: ("undoubtedly", "ad. 의심할 여지없이"),
    598: ("agenda", "n. 안건"),
    599: ("intention", "n. 의도"),
    600: ("dependent", "a. 의존하는, 달려있는"),
    601: ("medical", "a. 의학의"),
    602: ("exotic", "a. 이국적인"),
    603: ("lead", "v. 이끌다"),
    604: ("migration", "n. 이민"),
    605: ("resume", "n. 이력서 v. 재시하다"),
    606: ("consist", "v. 이루어져있다"),
    607: ("board of directors", "n. 이사회"),
    608: ("ideal", "a. 이상적인"),
    609: ("speak", "v. 이야기하다"),
    610: ("utilization", "n. 이용"),
    611: ("available", "a. 이용 가능한"),
    612: ("unavailable", "a. 이용 불가능한"),
    613: ("access", "n. 접근 v. 접근하다"),
    614: ("occupancy", "n. 점유, 차지함"),
    615: ("utilize", "v. 이용하다"),
    616: ("profit", "n. 이익"),
    617: ("benefit", "n. 이익"),
    618: ("previously", "ad. 이전에"),
    619: ("beforehand", "ad. 미리"),
    620: ("former", "a. 이전의"),
    621: ("previous", "a. 이전의"),
    622: ("advantage", "n. 이점, 장점"),
    623: ("understanding", "n. 이해"),
    624: ("implementation", "n. 이행, 실행"),
    625: ("anonymous", "a. 익명의"),
    626: ("familiarize", "v. 익숙케 하다"),
    627: ("authorize", "v. 인정하다, 승인하다"),
    628: ("popular", "a. 인기 있는"),
    629: ("patience", "n. 인내"),
    630: ("patient", "a. 인내심 있는 n. 환자"),
    631: ("salute", "v. 인사하다"),
    632: ("greet", "v. 인사하다"),
    633: ("impression", "n. 인상"),
    634: ("takeover", "v. 인수하다"),
    635: ("perception", "n. 인식, 지각"),
    636: ("personnel", "a. 인사의 n. 직원"),
    637: ("adjacent", "a. 인접한"),
    638: ("acknowledge", "v. 인정하다, 받아들이다"),
    639: ("artificial", "a. 인공적인"),
    640: ("intercom", "n. 구내전화"),
    641: ("prestigious", "a. 명망있는, 유명한"),
    642: ("temporarily", "ad. 임시적으로"),
    643: ("dedicated", "a. 헌신적인"),
    644: ("arise", "v. 일어나다"),
    645: ("undertake", "v. 떠맡다"),
    646: ("accordance", "n. 일치"),
    647: ("correspondence", "n. 서신교환"),
    648: ("illegible", "a. 읽기 어려운"),
}
page_7 = {
    649: ("forfeit", "v. 잃다 n. 박탈, 추징금"),
    650: ("wage", "n. 임금"),
    651: ("assignment", "n. 임무, 할당업무"),
    652: ("tentative", "a. 임시적인, 잠정적인"),
    653: ("board room", "n. 이사회 회의실"),
    654: ("randomly", "ad. 무작위로"),
    655: ("entrance", "n. 입구"),
    656: ("deposit", "n. 보증금 v. 입금하다"),
    657: ("wear", "v. 입고 있다"),
    658: ("mastermind", "n. 지도자 v. 조종하다"),
    659: ("admission", "n. 입장"),
    660: ("bid", "n. 입찰 v. 입찰하다"),
    661: ("bidder", "n. 입찰자"),
    662: ("surplus", "n. 과잉 a. 여분의"),
    663: ("qualification", "n. 자격요건"),
    664: ("quality", "n. 품질"),
    665: ("eligible", "a. 자격있는"),
    666: ("qualified", "a. 자격을 갖춘"),
    667: ("eligible", "a. 자격을 갖춘 n. 적임자"),
    668: ("licence", "n. 면허 v. 면허를주다"),
    669: ("urging", "a. 촉구하는"),
    670: ("fund", "n. 자금 v. 투자하다"),
    671: ("thermostat", "n. 온도조절장치"),
    672: ("escalator", "n. 에스컬레이터, 상승"),
    673: ("automatically", "ad. 자동적으로"),
    674: ("automatical", "a. 자동적인"),
    675: ("automate", "v. 자동화하다"),
    676: ("broom", "n. 빗자루"),
    677: ("voluntarily", "ad. 자발적으로"),
    678: ("asset", "n. 자산"),
    679: ("memoirs", "n. 회고록"),
    680: ("charity", "n. 자선"),
    681: ("confident", "a. 자신감있는"),
    682: ("ecology", "n. 생태학"),
    683: ("resource", "n. 자원"),
    684: ("retain", "v. 보류하다"),
    685: ("frequently", "ad. 자주, 빈번하게"),
    686: ("autograph", "n. 자필서명 v. 서명하다"),
    687: ("subsidiary", "a. 부차적인"),
    688: ("operational", "a. 운영상의"),
    689: ("operate", "v. 운영하다, 작동하다"),
    690: ("work load", "n. 업무량"),
    691: ("fine print", "n. 작은 활자"),
    692: ("acquaint", "v. 통지하다, 알려주다"),
    693: ("mistakenly", "ad. 실수로"),
    694: ("lock", "v. 잠그다 n. 자물쇠"),
    695: ("potential", "a. 잠재적인"),
    696: ("potentially", "ad. 잠재적으로"),
    697: ("chat", "v. 잡담하다 n. 잡담"),
    698: ("absenteeism", "n. 장기 결석"),
    699: ("prolonged", "a. 장기의, 긴 기간의"),
    700: ("scene", "n. 장면"),
    701: ("equipment", "n. 장비"),
    702: ("location", "n. 장소"),
    703: ("decorate", "v. 장식하다"),
    704: ("drape", "v. 주름을 잡다"),
    705: ("device", "n. 장비, 기기"),
    706: ("renewal", "n. 재개, 재생"),
    707: ("stock", "n. 주식, 재고"),
    708: ("inventory", "n. 재고"),
    709: ("disaster", "n. 재난"),
    710: ("aptitude", "n. 적성"),
    711: ("ash tray", "n. 재떨이"),
    712: ("material", "n. 재료"),
    713: ("property", "n. 재산, 부동산"),
    714: ("rearrange", "v. 재배열하다"),
    715: ("financial", "a. 재정적인"),
    716: ("recognize", "v. 인식하다, 인정하다"),
    717: ("recycling", "n. 재활용"),
    718: ("tray", "n. 쟁반"),
    719: ("eminent", "a. 저명한"),
    720: ("prominent", "a. 중요한"),
    721: ("scale", "n. 규모, 저울"),
    722: ("defy", "v. 도전하다"),
    723: ("aggressively", "ad. 공격적으로"),
    724: ("active", "a. 활동적인"),
    725: ("legitimate", "a. 합법적인"),
    726: ("adjust", "v. 조정하다"),
    727: ("deficit", "n. 적자, 부족액"),
    728: ("appropriately", "ad. 적절하게"),
    729: ("proper", "a. 적절한"),
    730: ("appropriate", "a. 적절한"),
    731: ("adequately", "ad. 충분하게"),
    732: ("perfection", "n. 완벽"),
    733: ("electricity", "n. 전기"),
    734: ("power", "n. 전기, 전원"),
    735: ("convey", "v. 나르다"),
    736: ("strategy", "n. 전략"),
    737: ("strategically", "ad. 전략적으로"),
    738: ("strategic", "a. 전략적인"),
    739: ("unprecedented", "a. 전례없는, 유례없는"),
    740: ("outlook", "n. 조망"),
    741: ("prospect", "n. 전망"),
    742: ("view", "n. 전망, 시각"),
    743: ("trained", "a. 훈련된"),
    744: ("expert", "n. 전문가"),
    745: ("specialist", "n. 전문가"),
    746: ("expertise", "n. 전문지식"),
    747: ("technically", "ad. 기술적으로"),
    748: ("professional", "a. 전문적인 n. 전문가"),
    749: ("overall", "ad. 전체적으로"),
    750: ("wire", "n. 전선"),
    751: ("exhibitor", "n. 전시자, 출품자"),
    752: ("display", "v. 전시하다"),
    753: ("exhibit", "v. 전시하다"),
    754: ("exhibition", "n. 전시회"),
    755: ("full time job", "n. 전일근무"),
    756: ("predecessor", "n. 전임자"),
}
page_8 = {
    757: ("microwave oven", "n. 전자레인지"),
    758: ("solely", "ad. 전적으로"),
    759: ("entire", "a. 전체의"),
    760: ("traditionally", "ad. 전통적으로"),
    761: ("traditional", "a. 전통적인"),
    762: ("spreadsheet", "n. 정산표"),
    763: ("convert", "v. 전환하다, 바꾸다"),
    764: ("impending", "a. 절박한"),
    765: ("economy", "n. 절약, 경제"),
    766: ("save", "v. 절약하다, 아끼다"),
    767: ("procedural", "a. 절차의"),
    768: ("increasingly", "ad. 점점 더"),
    769: ("gradually", "ad. 점진적으로"),
    770: ("gradual", "a. 점진적인, 점증적인"),
    771: ("approach", "v. 접근하다 n. 접근"),
    772: ("fold", "v. 접다"),
    773: ("plate", "n. 접시"),
    774: ("dish", "n. 접시, 음식"),
    775: ("sophisticated", "a. 정교한"),
    776: ("exquisite", "a. 절묘한, 정교한"),
    777: ("periodical", "n. 정기간행물 a. 정기적인"),
    778: ("regularly", "ad. 정기적으로"),
    779: ("routinely", "ad. 일상적으로"),
    780: ("regular", "a. 정기적인"),
    781: ("justify", "v. 정당화하다"),
    782: ("organize", "v. 정돈하다, 조직하다"),
    783: ("information", "n. 정보"),
    784: ("informed", "a. 잘 아는"),
    785: ("normal", "a. 보통의"),
    786: ("normally", "ad. 평상시대로"),
    787: ("inaugurate", "v. 취임하게 하다"),
    788: ("tablet", "n. 평판, 태블릿기기"),
    789: ("cordiality", "n. 진심, 정중함"),
    790: ("cordial", "a. 다정한"),
    791: ("stationary", "a. 정지된, 고정된"),
    792: ("purify", "v. 정화하다"),
    793: ("accurately", "ad. 정확하게"),
    794: ("exactly", "ad. 정확하게"),
    795: ("precisely", "ad. 정밀하게"),
    796: ("accurate", "a. 정확한"),
    797: ("issue", "n. 호, 발행, 문제"),
    798: ("eliminate", "v. 제거하다"),
    799: ("remove", "v. 제거하다"),
    800: ("offer", "v. 제공하다"),
    801: ("properly", "ad. 적절하게"),
    802: ("present", "v. 제안하다, a. 존재하는"),
    803: ("suggestion", "n. 제안"),
    804: ("pharmaceutical", "a. 제약의, 제약사의"),
    805: ("fabricate", "v. 위조하다"),
    806: ("enact", "v. 제정하다"),
    807: ("manufacturer", "n. 제조업자"),
    808: ("submission", "n. 제출물"),
    809: ("submit", "v. 제출하다"),
    810: ("line", "n. 제품군, 선 v. 늘어서다"),
    811: ("unlimited", "a. 무제한의"),
    812: ("circumscribe", "v. 제한하다"),
    813: ("confine", "v. 제한하다, 가두다"),
    814: ("restrict", "v. 제한하다"),
    815: ("segment", "n. 조각 v. 분할하다"),
    816: ("term", "n. 조건, 기간, 용어"),
    817: ("coherent", "a. 일치하는, 일관성있는"),
    818: ("assemble", "v. 조립하다"),
    819: ("investigation", "n. 조사"),
    820: ("inspection", "n. 검사, 점검, 시찰"),
    821: ("examine", "v. 검사하다, 살피다"),
    822: ("check", "v. 검사하다 n. 수표"),
    823: ("careful", "a. 조심스러운"),
    824: ("cautiously", "ad. 조심스럽게"),
    825: ("advise", "v. 조언하다"),
    826: ("manipulation", "n. 조작"),
    827: ("coordination", "n. 조직, 협동"),
    828: ("meditation", "n. 명상"),
    829: ("coordinate", "v. 조율하다"),
    830: ("provision", "n. 준비 v. 공급하다"),
    831: ("honor", "n. 영광 v. 존경을 표하다"),
    832: ("respectful", "a. 예의바른, 공손한"),
    833: ("narrow", "a. 좁은 v. 좁히다, 축소하다"),
    834: ("engage", "v. 종사하다"),
    835: ("comprehensive", "a. 종합적인"),
    836: ("seating", "n. 좌석"),
    837: ("periodically", "ad. 정기적으로"),
    838: ("note", "v. 주목하다"),
    839: ("order", "v. 주문하다 n. 주문"),
    840: ("customize", "v. 주문제작하다"),
    841: ("chef", "n. 요리사"),
    842: ("injection", "n. 주사"),
    843: ("shot", "n. 주사, 예방주사"),
    844: ("address", "v. 다루다, 처리하다, 연설하다"),
    845: ("principal", "a. 주요한 n. 교장선생님"),
    846: ("chief", "n. 장, 우두머리"),
    847: ("carefully", "ad. 주의깊게"),
    848: ("attention", "n. 주의"),
    849: ("caution", "n. 조심"),
    850: ("infusion", "n. 주입"),
    851: ("infuse", "v. 주입하다"),
    852: ("claim", "v. 주장하다"),
    853: ("allegedly", "ad. 이른바, 주장에 의하면"),
    854: ("hesitate", "v. 망설이다"),
    855: ("subject", "n. 주제, 과목"),
    856: ("shareholder", "n. 주주"),
    857: ("park", "v. 주차하다"),
    858: ("host", "n. 주인"),
    859: ("residence", "n. 주택"),
    860: ("housing", "n. 주택"),
    861: ("mortgage", "n. 저당 v. 저당잡히다"),
    862: ("arrangements", "n. 준비"),
    863: ("compliance", "n. 준수 (따르는 것)"),
    864: ("observance", "n. 준수"),
}
page_9 = {
    865: ("comply", "v. 준수하다"),
    866: ("dwindle", "v. 작아지다"),
    867: ("lower", "v. 낮추다 a. 더 낮은"),
    868: ("reduce", "v. 줄이다"),
    869: ("cut", "v. 절단하다"),
    870: ("halt", "v. 중단하다"),
    871: ("disruption", "n. 붕괴"),
    872: ("discontinue", "v. 중지하다"),
    873: ("neutrality", "n. 중립"),
    874: ("importantly", "ad. 중요하게"),
    875: ("arbitration", "n. 중재, 조정"),
    876: ("moderator", "n. 의장, 진행자, 중재자"),
    877: ("instantly", "ad. 즉각적으로"),
    878: ("immediately", "ad. 즉시"),
    879: ("readily", "ad. 기꺼이, 즉시"),
    880: ("promptly", "ad. 신속하게"),
    881: ("improvise", "v. 즉흥적으로 하다"),
    882: ("increment", "n. 증진, 증대"),
    883: ("increase", "n. 증가 v. 증진하다"),
    884: ("increasing", "a. 증가하는"),
    885: ("mounting", "n. 설치, 올려놓, 등단"),
    886: ("evidence", "n. 증거"),
    887: ("certification", "n. 증명서"),
    888: ("demonstrate", "v. 증명하다, 시연하다"),
    889: ("symptom", "n. 증상, 징후"),
    890: ("district", "n. 지역"),
    891: ("nomination", "n. 지명, 임명"),
    892: ("appoint", "v. 임명하다"),
    893: ("local", "a. 지역의"),
    894: ("municipal", "a. 지방의, 시의"),
    895: ("payment", "n. 납부, 지급"),
    896: ("payable", "a. 지급할수있는"),
    897: ("duration", "n. 지속, 내구"),
    898: ("persistent", "a. 끈질긴, 완고한"),
    899: ("sustain", "v. 유지하다, 떠받히다"),
    900: ("instruct", "v. 지도하다"),
    901: ("indigenous", "a. 토착의, 원산의"),
    902: ("area", "n. 지역, 분야"),
    903: ("community", "n. 지역사회, 공동체"),
    904: ("locally", "ad. 지역적으로"),
    905: ("applicant", "n. 지원자"),
    906: ("volunteer", "n. 지원자 v. 지원하다"),
    907: ("candidate", "n. 지원자, 선거후보자"),
    908: ("apply", "v. 지원하다"),
    909: ("level", "n. 수준, 정도, 단계"),
    910: ("spot", "n. 장소, 지점, 얼룩"),
    911: ("branch office", "n. 지점"),
    912: ("designated", "a. 지정된"),
    913: ("name", "v. 임명하다, 지정하다"),
    914: ("uphold", "v. 받들다, 지지하다"),
    915: ("outlay", "n. 비용, 경비, 지출"),
    916: ("expenditure", "n. 지출"),
    917: ("indicator", "n. 지시자"),
    918: ("basement", "n. 지하"),
    919: ("confront", "v. 직면하다, 마주하다"),
    920: ("square", "n. 정사각형 a. 정사각형의"),
    921: ("occupation", "n. 직업, 업무"),
    922: ("clerk", "n. 점원, 직원"),
    923: ("personally", "ad. 직접"),
    924: ("diagnosis", "n. 진단"),
    925: ("advance", "n. 진보"),
    926: ("progressive", "a. 진취적인, 진보하는"),
    927: ("state", "v. 진술하다 n. 진술"),
    928: ("cordially", "ad. 진심으로"),
    929: ("petition", "n. 청원, 진정"),
    930: ("seriously", "ad. 진지하게"),
    931: ("genuine", "a. 진품의, 진짜의"),
    932: ("progress", "n. 진보하다 v. 전진하다"),
    933: ("authentic", "a. 진짜의"),
    934: ("procedure", "n. 절차"),
    935: ("inquire", "v. 문의하다"),
    936: ("luggage", "n. 짐"),
    937: ("pack", "v. 짐을 싸다 n. 짐"),
    938: ("unload", "v. 짐을 내리다"),
    939: ("load", "v. 짐싣다 n. 짐, 업무, 일"),
    940: ("unpack", "v. 짐을 풀다"),
    941: ("compile", "v. 편집하다"),
    942: ("intense", "a. 심한"),
    943: ("concentrate", "v. 집중하다"),
    944: ("consensus", "n. 합의"),
    945: ("concourse", "n. 집합, 합류, 집합장소"),
    946: ("indication", "n. 지시, 지적, 암시"),
    947: ("shorten", "v. 줄이다"),
    948: ("short", "a. 짧은 ad. 간단하게"),
    949: ("crack", "v. 금가게 하다 n. 쨍 소리"),
    950: ("chase", "v. 추적하다 n. 추적"),
    951: ("balance", "n. 잔고 (은행잔고)"),
    952: ("garage", "n. 차고"),
    953: ("vehicle", "n. 탈것"),
    954: ("discriminate", "v. 차별하다"),
    955: ("difference", "n. 차이점"),
    956: ("discrepancy", "n. 모순"),
    957: ("occupy", "v. 차지하다, 맡다"),
    958: ("touchdown", "n. 착륙"),
    959: ("embark", "v. 출항하다, 착수하다"),
    960: ("exploit", "v. 착취하다 n. 공훈, 공적"),
    961: ("acclaim", "v. 갈채를 보내다 n. 환호"),
    962: ("entry", "n. 참가, 참가자, 참가물품"),
    963: ("participant", "n. 참석자"),
    964: ("participate", "v. 참석하다"),
    965: ("reference", "n. 참조사항"),
    966: ("attendee", "n. 참석자"),
    967: ("attend", "v. 참석하다"),
    968: ("participation", "n. 참가"),
    969: ("refer", "v. 참고하다"),
    970: ("depot", "n. 창고, 정류소"),
    971: ("founder", "n. 창립자"),
    972: ("creative", "a. 창조적인"),
}
page_10 = {
    973: ("create", "v. 창조하다"),
    974: ("generate", "v. 발생시키다"),
    975: ("mining", "n. 채굴"),
    976: ("bond", "n. 채권 v. 묶다, 담보잡히다"),
    977: ("vegetarian", "n. 채식주의자"),
    978: ("fill", "n. 채우다, 충원하다"),
    979: ("adopt", "v. 채택하다"),
    980: ("responsibility", "n. 책임, 책무"),
    981: ("liability", "n. 책임, 채무, 부담"),
    982: ("processing", "n. 처리"),
    983: ("dispose", "n. 처분하다"),
    984: ("asthma", "n. 천식"),
    985: ("ceiling", "n. 천장"),
    986: ("thoroughly", "ad. 철저하게"),
    987: ("bill", "v. 청구하다, 영수증"),
    988: ("format", "n. 체제, 대형"),
    989: ("constraint", "v. 통제"),
    990: ("stare", "v. 쳐다보다, 응시하다"),
    991: ("excess", "n. 초과분 a. 과도한"),
    992: ("initially", "ad. 처음에는"),
    993: ("microwave", "n. 초단파"),
    994: ("portrait", "n. 초상화"),
    995: ("draft", "n. 초안 v. 설계하다"),
    996: ("accelerate", "v. 가속하다"),
    997: ("turnover", "n. 총 매상, 회전율"),
    998: ("total", "n. 총액 a. 전체의"),
    999: ("chief executive officer", "n. 최고경영자"),
    1000: ("lately", "ad. 최근에"),
    1001: ("recently", "ad. 최근에"),
    1002: ("recent", "a. 최근의"),
    1003: ("maximum", "n. 최대량 a. 최대의"),
    1004: ("minimum", "n. 최소량 a. 최소의"),
    1005: ("state-of-the-art", "a. 최신의"),
    1006: ("momentum", "n. 추진력, 가속도, 추진력"),
    1007: ("speculation", "n. 추측, 임시수고"),
    1008: ("accumulation", "n. 축적"),
    1009: ("accumulate", "v. 축적하다"),
    1010: ("accrue", "v. 축적하다"),
    1011: ("congratulate", "v. 축하하다"),
    1012: ("exit", "n. 출구 v. 탈출하다"),
    1013: ("departure", "n. 출발"),
    1014: ("depart", "v. 출발하다"),
    1015: ("maternity leave", "n. 출산휴가"),
    1016: ("attendance", "n. 출석"),
    1017: ("attendant", "n. 수행원 a. 출석한"),
    1018: ("turn out", "n. 출석률 v. 밝혀지다"),
    1019: ("launch", "v. 출시하다"),
    1020: ("accessible", "a. 출입가능한"),
    1021: ("advice", "n. 충고"),
    1022: ("sufficiently", "ad. 충분하게"),
    1023: ("ample", "a. 충분한"),
    1024: ("cancellation", "n. 취소"),
    1025: ("vulnerable", "a. 취약한"),
    1026: ("gauge", "n. 치수 v. 측정하다"),
    1027: ("story", "n. 층수"),
    1028: ("remedy", "n. 치료 v. 고치다, 치료하다"),
    1029: ("treat", "n. 취급하다 n. 한턱내기"),
    1030: ("skyrocket", "v. 치솟다, 물가가 급등하다"),
    1031: ("friendly", "a. 친근한"),
    1032: ("kindly", "a. 친절한"),
    1033: ("calmly", "ad. 침착하게"),
    1034: ("stagnant", "a. 침체된, 불경기인"),
    1035: ("infringement", "n. 침해, 법규위반"),
    1036: ("praise", "n. 칭찬 v. 칭찬하다"),
    1037: ("compliment", "n. 칭찬 v. 칭찬하다"),
    1038: ("electronically", "ad. 전자적으로"),
    1039: ("mustache", "n. 콧수염"),
    1040: ("agreeably", "ad. 흔쾌히, 기꺼이"),
    1041: ("substantially", "ad. 상당하게"),
    1042: ("innate", "a. 타고난"),
    1043: ("ride", "v. 타다 n. 차편"),
    1044: ("compromise", "n. 타협 v. 타협하다"),
    1045: ("desalinate", "v. 염분을 제거하다"),
    1046: ("indulge", "v. 채우다, 충족시키다"),
    1047: ("search", "v. 찾다 n. 검색"),
    1048: ("board", "n. 이사회 v. 타다"),
    1049: ("stance", "n. 자세, 입장"),
    1050: ("cab", "n. 택시"),
    1051: ("foundation", "n. 토대, 기초, 설립"),
    1052: ("discussion", "n. 토론"),
    1053: ("discuss", "v. 토론하다"),
    1054: ("commuter", "n. 통근자"),
    1055: ("commute", "v. 통근하다"),
    1056: ("aisle", "n. 통로"),
    1057: ("commerce", "n. 통상, 상업, 거래"),
    1058: ("communication", "n. 통신"),
    1059: ("notification", "n. 통지"),
    1060: ("notify", "v. 통지하다"),
    1061: ("impassable", "a. 통행할 수 없는"),
    1062: ("investment", "n. 투자"),
    1063: ("portfolio", "n. 자산, 작품집"),
    1064: ("investor", "n. 투자자"),
    1065: ("invest", "v. 투자하다"),
    1066: ("specialize in", "v. 전문으로 하다"),
    1067: ("privilege", "n. 특권"),
    1068: ("feature", "n. 특징 v. 다루다"),
    1069: ("characteristic", "a. 특징적인"),
    1070: ("distinguish", "v. 구별하다"),
    1071: ("patent", "n. 특허권"),
    1072: ("especially", "ad. 특히"),
    1073: ("particularly", "ad. 특히"),
    1074: ("sturdy", "a. 튼튼한"),
    1075: ("robust", "a. 튼튼한"),
    1076: ("surely", "ad. 틀림없이"),
    1077: ("gratuity", "n. 팁, 보수, 상금"),
    1078: ("demolish", "v. 파괴하다, 허물다"),
    1079: ("faction", "n. 파벌"),
    1080: ("breakage", "n. 파손, 파괴, 손상"),
}
page_11 = {
    1081: ("strike", "v. 파업하다 n. 파업"),
    1082: ("reptile", "v. 파충류"),
    1083: ("part-time job", "n. 파트타임근무"),
    1084: ("judge", "n. 판사, 심사위원 v. 판단하다"),
    1085: ("dealer", "n. 판매원"),
    1086: ("cardboard box", "n. 판지 상자"),
    1087: ("carton", "n. 통, 상자"),
    1088: ("conveniently", "ad. 편리하게"),
    1089: ("convenient", "a. 편리한"),
    1090: ("convenience", "n. 편의"),
    1091: ("amenity", "n. 편의시설, 설비"),
    1092: ("editor", "n. 편집자"),
    1093: ("edit", "v. 편집하다"),
    1094: ("partially", "ad. 편파적으로"),
    1095: ("unfold", "v. 펴다"),
    1096: ("appraisal", "n. 평가, 감정"),
    1097: ("estimation", "n. 평가"),
    1098: ("evaluation", "n. 평가"),
    1099: ("evaluate", "v. 평가하다"),
    1100: ("appraise", "v. 평가하다"),
    1101: ("average", "n. 평균 a. 평균의"),
    1102: ("parallel", "a. 평행한 n. 평행 ad. 평행하게"),
    1103: ("abolish", "v. 폐지하다, 절폐하다"),
    1104: ("aspiration", "n. 포부, 야망"),
    1105: ("embrace", "v. 포옹하다"),
    1106: ("include", "v. 포함하다"),
    1107: ("encompass", "v. 포함하다, 둘러싸다"),
    1108: ("soar", "v. 높이오르다, 급등하다"),
    1109: ("plummet", "v. 급락하다"),
    1110: ("specimen", "n. 표본, 샘플"),
    1111: ("token", "n. 표, 상품권"),
    1112: ("standard", "n. 표준"),
    1113: ("quality", "n. 품질"),
    1114: ("scenery", "n. 경치"),
    1115: ("fatigue", "n. 피로"),
    1116: ("need", "n. 필요 v. 필요로하다"),
    1117: ("requirement", "n. 필요조건, 필수자격요건"),
    1118: ("fall", "v. 떨어지다"),
    1119: ("sewage", "n. 하수, 오물"),
    1120: ("degree", "n. 학위, 정도"),
    1121: ("stack", "n. 무더기, 퇴적"),
    1122: ("quota", "n. 할당액, 몫"),
    1123: ("allocate", "v. 할당하다"),
    1124: ("installment", "n. 할부"),
    1125: ("discount vouchers", "n. 할인쿠폰"),
    1126: ("discount", "n. 할인"),
    1127: ("figure", "n. 수치, 숫자"),
    1128: ("combined", "a. 결합된"),
    1129: ("merge", "v. 합병하다"),
    1130: ("consistently", "ad. 지속적으로"),
    1131: ("antibiotic", "n. 항생제"),
    1132: ("jar", "n. 항아리, 단지"),
    1133: ("solution", "n. 해법, 용액"),
    1134: ("settle", "v. 해결하다, 정착시키다"),
    1135: ("dismiss", "v. 해고하다"),
    1136: ("interpretation", "n. 해석, 통역"),
    1137: ("act", "n. 행위, 법 v. 행하다"),
    1138: ("happiness", "n. 행복"),
    1139: ("vendor", "n. 행상, 공급업체"),
    1140: ("proceed", "v. 행하다, 나아가다"),
    1141: ("scent", "n. 향기"),
    1142: ("permit", "v. 허락하다 n. 허가증"),
    1143: ("allowance", "n. 허용량"),
    1144: ("dedication", "n. 헌신"),
    1145: ("commitment", "n. 헌신, 책무"),
    1146: ("dedicated", "a. 헌신적인"),
    1147: ("malign", "a. 해로운, 유해한"),
    1148: ("health and fitness club", "n. 헬스클럽"),
    1149: ("rinse", "v. 헹구다"),
    1150: ("revolution", "n. 혁명"),
    1151: ("revolutionary", "a. 혁명적인"),
    1152: ("innovation", "n. 혁신"),
    1153: ("innovative", "a. 혁신적인"),
    1154: ("cash", "n. 현금"),
    1155: ("contemporary", "a. 현대의, 동시대의"),
    1156: ("modernize", "v. 현대화하다"),
    1157: ("microscope", "n. 현미경"),
    1158: ("realistically", "ad. 현실적으로"),
    1159: ("current events", "n. 시사, 시사문제연구"),
    1160: ("currently", "ad. 현재"),
    1161: ("presently", "ad. 현재"),
    1162: ("current", "a. 현재의"),
    1163: ("markedly", "ad. 현저하게, 두드러진"),
    1164: ("remarkable", "a. 현저한"),
    1165: ("cooperation", "n. 협동"),
    1166: ("collaborate", "v. 협동하다"),
    1167: ("cooperative", "a. 협조적인"),
    1168: ("cooperatively", "ad. 협조적으로"),
    1169: ("negotiation", "n. 협상"),
    1170: ("incentive", "n. 보너스, 장려책"),
    1171: ("appeal", "v. 호소하다"),
    1172: ("pager", "n. 삐삐, 무선호출기"),
    1173: ("stapler", "n. 스테이플러, 호치키스"),
    1174: ("courtesy bus", "n. 무료셔틀버스"),
    1175: ("compatible", "a. 양립하는, 조화되는"),
    1176: ("brisk", "a. 활발한"),
    1177: ("confusion", "n. 혼동"),
    1178: ("congestion", "n. 혼잡"),
    1179: ("heavy", "a. 심한"),
    1180: ("public relation", "n. 홍보"),
    1181: ("flood", "n. 홍수"),
    1182: ("infuriate", "v. 화나게하다"),
    1183: ("gallery", "n. 화랑"),
    1184: ("chemical", "a. 화학의"),
    1185: ("unwavering", "a. 확고한"),
    1186: ("established", "a. 확립된"),
    1187: ("confidence", "n. 확신, 신뢰"),
    1188: ("convince", "v. 확신시키다, 납득시키다"),
}
page_12 = {
    1189: ("locate", "v. 찾다, 위치하다"),
    1190: ("volatile", "a. 변덕스러운, 위험성의"),
    1191: ("affordable", "a. 가격이 알맞은"),
    1192: ("tenant", "n. 세입자"),
    1193: ("outweigh", "v. 능가하다, 더중요하다"),
    1194: ("complex", "a. 복잡한 n. 단지"),
    1195: ("reschedule", "v. 재조정하다"),
    1196: ("dice", "n. 주사위 v. 썰다"),
    1197: ("inflict", "v. 가하다"),
    1198: ("spacious", "a. 넓은"),
    1199: ("relocate", "v. 이전하다"),
    1200: ("breakthrough", "n. 돌파구"),
    1201: ("disperse", "v. 해산하다"),
    1202: ("waive", "v. 면제해주다"),
    1203: ("conform", "v. 순응하다"),
    1204: ("directions", "n. 길안내"),
    1205: ("forecast", "n. 예보"),
    1206: ("inclement", "a. 궂은"),
    1207: ("lane", "n. 차선"),
    1208: ("habitat", "n. 서식지"),
    1209: ("securely", "ad. 안전하게"),
    1210: ("assume", "v. 추정하다"),
    1211: ("delinquent", "a. 채무불이행의"),
    1212: ("incur", "v. 초래하다"),
    1213: ("appointment", "n. 임명"),
    1214: ("article", "n. 기사, 조항"),
    1215: ("classified section", "n. 광고면"),
    1216: ("recruit", "v. 모집하다 n. 신입사원"),
    1217: ("prescribe", "v. 처방을 내리다"),
    1218: ("dilute", "v. 희석시키다"),
    1219: ("withdrawal", "n. 철회, 취소, 인출"),
    1220: ("rack", "n. 선반, 걸이"),
    1221: ("blue chip", "n. 우량주"),
    1222: ("attribute", "v. 탓으로 돌리다"),
    1223: ("yield", "n. 산출량 v. 산출하다"),
    1224: ("occur", "v. 발생하다"),
    1225: ("path", "n. 통로"),
    1226: ("obstruct", "v. 막다"),
    1227: ("considerate", "a. 사려깊은"),
    1228: ("utensil", "n. 도구"),
    1229: ("distract", "v. 흔들리다"),
    1230: ("enhance", "v. 향상시키다"),
    1231: ("unoccupied", "a. 비어있는"),
    1232: ("annotated", "a. (책)주석이 달린"),
    1233: ("procurement", "n. 입수"),
    1234: ("surface mail", "n. 보통우편, 선박우편"),
    1235: ("liquidate", "v. 변제하다"),
    1236: ("convene", "v. 소환하다"),
    1237: ("preside", "v. 주재하다"),
    1238: ("join", "v. 참가하다"),
    1239: ("oblige", "v. 의무를 지우다"),
    1240: ("regarding", "관하여"),
    1241: ("concerning", "관하여"),
    1242: ("radioactive", "a. 방사능의"),
    1243: ("contingent", "a. 임시의"),
    1244: ("depend", "v. 의지하다"),
    1245: ("reward", "n. 보상"),
    1246: ("subsidize", "v. 보조금을 주다"),
    1247: ("engrave", "v. 새기다"),
    1248: ("affect", "v. 영향을 주다"),
    1249: ("accustomed", "a. 익숙한"),
    1250: ("match", "n. 시합"),
    1251: ("brief", "a. 간략한"),
    1252: ("direct", "a. 직접적인"),
    1253: ("compensate", "v. 보상하다"),
    1254: ("assure", "v. 확언하다"),
    1255: ("commensurate", "a. 상응하는"),
    1256: ("regardless of", "~에 상관없이"),
    1257: ("contact", "v. 연락하다"),
    1258: ("regard", "v. 간주하다"),
    1259: ("run", "v. 운영하다"),
    1260: ("manage", "v. 운영하다"),
    1261: ("replace", "v. 대체하다"),
    1262: ("surpass", "v. 능가하다"),
    1263: ("polish", "v. 광택을 내다"),
    1264: ("hold", "v. 개최하다"),
    1265: ("prevent", "v. 막다"),
    1266: ("bear", "v. 참다"),
    1267: ("accommodate", "v. 수용하다"),
    1268: ("spend", "v. (시간, 돈)쓰다"),
    1269: ("cause", "n. 원인 v. 야기시키다"),
    1270: ("schedule", "v. 일정을 잡다 n. 일정표"),
    1271: ("curtail", "v. 축소시키다"),
    1272: ("exceed", "v. 초과하다"),
    1273: ("capable", "a. 유능한"),
    1274: ("opposite", "a. 맞은편의"),
    1275: ("demoralize", "v. 사기를 꺾다"),
    1276: ("suspect", "v. 의심하다"),
    1277: ("edition", "n. 판, 호"),
    1278: ("allow", "v. 허락하다"),
    1279: ("liable", "a. ~할것같은"),
    1280: ("tend", "v. 경향이 있다"),
    1281: ("place", "v. 놓다"),
    1282: ("likely", "a. ~할것같은"),
    1283: ("entitle", "v. 자격을 주다"),
    1284: ("following", "a. 다음의"),
    1285: ("quarterly", "a. 분기별 ad. 분기별로"),
    1286: ("dose", "n. 복용량"),
    1287: ("bilingual", "a. 이중언어의"),
    1288: ("quarter", "n. 4분의 1"),
    1289: ("price", "v. 가격을 매기다"),
    1290: ("value", "n. 가치"),
    1291: ("furnished", "a. 가구가 갖추어진"),
    1292: ("barely", "ad. 거의~하지 않다"),
    1293: ("proximity", "n. 접근성"),
    1294: ("possibility", "n. 가능성"),
    1295: ("probable", "a. 가능성있는"),
    1296: ("chance", "n. 기회"),
}
page_13 = {
    1297: ("possible", "a. 가능한, 할 수 있는"),
    1298: ("franchisor", "n. 프랜차이즈 주는 기업"),
    1299: ("franchise", "n. 가맹권"),
    1300: ("franchisee", "n. 가맹점"),
    1301: ("drought", "n. 가뭄, 한발"),
    1302: ("refreshment", "n. 간식"),
    1303: ("fumes", "n. 가스"),
    1304: ("edge", "n. 가장자리"),
    1305: ("domestic", "a. 국내의, 자국의"),
    1306: ("counterfeit", "a. 가짜의 v. 위조하다"),
    1307: ("worth", "a. 가치가 있는"),
    1308: ("depreciation", "n. 가치하락"),
    1309: ("respective", "a. 각각의"),
    1310: ("succinct", "a. 간결한"),
    1311: ("oversight", "n. 감독, 감시"),
    1312: ("continental breakfast", "n. 간단한 아침식사"),
    1313: ("intervention", "n. 간섭, 중재"),
    1314: ("publication", "n. 간행, 출판물"),
    1315: ("rake", "v. 긁어모으다 n. 갈퀴"),
    1316: ("sense", "n. 감각 v. 감지하다"),
    1317: ("custody", "n. 관리, 양육권"),
    1318: ("supervision", "n. 감독"),
    1319: ("supervisor", "n. 감독자, 상사"),
    1320: ("supervise", "v. 감독하다"),
    1321: ("oversee", "v. 내려다보다"),
    1322: ("appreciation", "n. 감상, 감사"),
    1323: ("reduction", "n. 감소, 절감"),
    1324: ("wane", "v. 줄어들다"),
    1325: ("decline", "v. 감소하다, 거절하다"),
    1326: ("decrease", "v. 줄다, 줄이다 n. 감소"),
    1327: ("diminish", "v. 줄다, 감소시키다"),
    1328: ("connoisseur", "n. 감정인"),
    1329: ("deck", "n. 갑판"),
    1330: ("costly", "a. 비싼"),
    1331: ("expensive", "a. 비싼"),
    1332: ("auditorium", "n. 강당"),
    1333: ("powerful", "a. 강한"),
    1334: ("precipitation", "n. 강수 (강우량)"),
    1335: ("lecture", "n. 강의 v. 강연하다"),
    1336: ("emphasis", "n. 강조"),
    1337: ("emphatic", "a. 강조하는"),
    1338: ("strongly", "ad. 강하게"),
    1339: ("reinforcement", "n. 강화"),
    1340: ("reinforce", "v. 강화하다"),
    1341: ("consolidate", "v. 통합하다"),
    1342: ("fortify", "v. 강화하다"),
    1343: ("equip", "v. 장비를 갖추다"),
    1344: ("development", "n. 발전"),
    1345: ("separately", "ad. 각각, 따로따로"),
    1346: ("improve", "v. 개선하다"),
    1347: ("individually", "ad. 개인적으로"),
    1348: ("personal", "a. 개인의"),
    1349: ("renovate", "v. 개조하다"),
    1350: ("personality", "n. 개성, 인격"),
    1351: ("pioneer", "n. 개척자"),
    1352: ("renew", "v. 새롭게 하다"),
    1353: ("conglomerate", "n. 대기업 v. 결합하다"),
    1354: ("huge", "a. 거대한"),
    1355: ("deal", "n. 거래"),
    1356: ("transaction", "n. 거래"),
    1357: ("hardly", "ad. 거의 ~ 아니다"),
    1358: ("nearly", "ad. 거의, 대략"),
    1359: ("refuse", "v. 거절하다, 거부하다"),
    1360: ("rough", "a. 거친"),
    1361: ("fitness", "n. 건강"),
    1362: ("health", "n. 건강"),
    1363: ("checkup", "n. 건강검진"),
    1364: ("hand", "v. 건네주다"),
    1365: ("floor", "n. 작업장"),
    1366: ("construction", "n. 건설"),
    1367: ("constructive", "a. 건설적인"),
    1368: ("dry", "a. 건조한"),
    1369: ("inspect", "v. 검사하다"),
    1370: ("thrifty", "a. 검소한"),
    1371: ("censorship", "n. 검열"),
    1372: ("review", "v. 검토하다 n. 후기"),
    1373: ("bulletin board", "n. 게시판"),
    1374: ("encouragement", "n. 격려"),
    1375: ("inspire", "v. 영감을 주다"),
    1376: ("encourage", "v. 격려하다"),
    1377: ("gap", "v. 갈라지다 n. 틈"),
    1378: ("undergo", "v. 겪다"),
    1379: ("probationary", "a. 견습중인"),
    1380: ("tow", "v. 견인하다"),
    1381: ("estimate", "n. 견적서"),
    1382: ("quote", "v. 견적서"),
    1383: ("consequence", "n. 결과"),
    1384: ("result", "n. 결과"),
    1385: ("eventually", "ad. 결국에"),
    1386: ("resolution", "n. 결심"),
    1387: ("decision", "n. 결정"),
    1388: ("conclusion", "n. 결말"),
    1389: ("defective", "a. 결함 있는"),
    1390: ("combination", "n. 결합"),
    1391: ("marriage", "n. 결혼"),
    1392: ("marital", "a. 혼인의"),
    1393: ("modestly", "ad. 겸손하게"),
    1394: ("landmark", "n. 경계표"),
    1395: ("revitalization", "n. 회복시키다"),
    1396: ("contestant", "n. 경기참가자"),
    1397: ("slowdown", "n. 경기침체"),
    1398: ("auction", "n. 경매"),
    1399: ("alert", "v. 경각심을 느끼다"),
    1400: ("management", "n. 경영진"),
    1401: ("occasion", "n. 경우"),
    1402: ("competition", "n. 경쟁"),
    1403: ("competitor", "n. 경쟁자"),
    1404: ("competitive", "a. 경쟁적인"),
}
page_14 = {
    1405: ("honk", "n. 경적 소리 v. 울다"),
    1406: ("economic", "a. 경제의"),
    1407: ("economical", "a. 경제적인, 절약하는"),
    1408: ("ceremony", "n. 의식"),
    1409: ("scenic", "a. 경치가 좋은"),
    1410: ("trend", "n. 경향"),
    1411: ("stair", "n. 계단"),
    1412: ("enlightening", "n. 계몽"),
    1413: ("calculation", "n. 계산"),
    1414: ("calculate", "v. 계산하다"),
    1415: ("continual", "a. 연속적인"),
    1416: ("continually", "ad. 계속적으로"),
    1417: ("contract", "v. 계약하다 n. 계약"),
    1418: ("contractor", "n. 계약자"),
    1419: ("stipulation", "n. 계약, 약정"),
    1420: ("affiliate", "v. 가입하다 n. 제휴사"),
    1421: ("seasonal", "a. 계절의"),
    1422: ("proposal", "n. 제안, 제안서"),
    1423: ("deplete", "v. 고갈소모시키다"),
    1424: ("client", "n. 고객"),
    1425: ("customer", "n. 고객"),
    1426: ("struggle", "v. 고군분투하다"),
    1427: ("account", "n. 계좌, 계정"),
    1428: ("consider", "v. 고려하다"),
    1429: ("sort", "v. 구별하다 n. 종류"),
    1430: ("consultant", "n. 컨설턴트"),
    1431: ("accuse", "v. 고소하다"),
    1432: ("adhere to", "v. 고수하다, 집착하다"),
    1433: ("devise", "v. 고안하다"),
    1434: ("employment", "n. 고용"),
    1435: ("employer", "n. 고용주"),
    1436: ("dignity", "n. 기품"),
    1437: ("knowingly", "ad. 고의로"),
    1438: ("deliberate", "a. 고의적인 v. 고려하다"),
    1439: ("malfunction", "n. 오작동"),
    1440: ("failure", "n. 실패"),
    1441: ("clip", "v. 자르다"),
    1442: ("remodel", "v. 개조하다"),
    1443: ("plunge", "v. 찌르다, 던지다"),
    1444: ("shortly", "ad. 곧"),
    1445: ("directly", "ad. 직접적으로"),
    1446: ("disclose", "v. 공개하다"),
    1447: ("release", "v. 출시하다"),
    1448: ("announcement", "n. 공지"),
    1449: ("public utilities", "n. 공공시설(전기,가스등)"),
    1450: ("utility", "n. 공익사업, 실용성"),
    1451: ("supply", "v. 공급하다"),
    1452: ("provide", "v. 제공하다"),
    1453: ("impartially", "ad. 공평정대하게"),
    1454: ("official", "a. 공식적인 n. 공무원"),
    1455: ("vacancy", "n. 결원, 공석"),
    1456: ("opening", "n. 결원, 공석, 구인"),
    1457: ("respectfully", "ad. 공손하게"),
    1458: ("rescue", "v. 구하다"),
    1459: ("vacant", "a. 텅 빈(자리가 빈)"),
    1460: ("officially", "ad. 공식적으로"),
    1461: ("formal", "a. 공식의"),
    1462: ("industrial", "a. 산업의"),
    1463: ("perform", "v. 수행하다"),
    1464: ("plant", "v. 심다 n. 공장, 식물"),
    1465: ("deduct", "v. 공제하다, 빼다"),
    1466: ("public phone", "n. 공중전화"),
    1467: ("pay phone", "n. 공중전화"),
    1468: ("overbill", "v. 과다지불하다"),
    1469: ("overcharge", "v. 과다청구하다"),
    1470: ("overprice", "v. 과도하게 가격을 매기다"),
    1471: ("relation", "n. 관계"),
    1472: ("irrelevant", "a. 관계없는, 무관한"),
    1473: ("involved", "a. 연루된, 관계있는"),
    1474: ("tourism", "n. 관광업"),
    1475: ("attraction", "n. 관광명소"),
    1476: ("interested", "a. 흥미를 가진"),
    1477: ("relate", "v. 관련시키다"),
    1478: ("managerial", "a. 관리의"),
    1479: ("control", "v. 관리하다 n. 관리"),
    1480: ("interest", "n. 관심, 이자"),
    1481: ("tolerance", "n. 관용"),
    1482: ("aspect", "n. 측면"),
    1483: ("advertisement", "n. 광고"),
    1484: ("advertising", "n. 광고"),
    1485: ("commercial", "n. 광고 a. 상업적인"),
    1486: ("advertise", "v. 광고하다"),
    1487: ("expansive", "a. 광범위한"),
    1488: ("extensive", "a. 광범위한"),
    1489: ("impressive", "a. 인상 깊은"),
    1490: ("course", "n. 진로"),
    1491: ("shift", "n. 교대근무 v. 전환하다"),
    1492: ("alternate", "a. 교체의 v. 번갈아하다"),
    1493: ("proofreading", "n. 교정"),
    1494: ("proofread", "v. 교정하다, 수정하다"),
    1495: ("intersection", "n. 교차로"),
    1496: ("cross", "a. 가로지르는 ad. 가로질러"),
    1497: ("deadlock", "n. 막힘, 교착상태"),
    1498: ("fare", "n. 요금"),
    1499: ("traffic jam", "n. 교통체증"),
    1500: ("swap", "v. 교환하다, 바꾸다"),
    1501: ("subscription", "n. 구독, 기부금"),
    1502: ("purchase", "v. 구매하다"),
    1503: ("compose", "v. 구성하다, 작곡하다"),
    1504: ("structure", "n. 구조"),
    1505: ("restructure", "v. 개조하다"),
    1506: ("specific", "a. 특정한"),
    1507: ("compartment", "n. 칸막이, 구획 v. 나누다"),
    1508: ("international", "a. 국제적인"),
    1509: ("firmly", "ad. 공고히, 굳게"),
    1510: ("strand", "v. 좌초시키다"),
    1511: ("recommend", "v. 추천하다"),
    1512: ("right", "n. 권리"),
}
page_15 = {
    1513: ("authority", "n. 권위"),
    1514: ("authorization", "n. 허가,허가서"),
    1515: ("code", "n. 법, 규칙"),
    1516: ("lax", "a. 느슨한"),
    1517: ("overtime", "n. 초과근무 a. 시간외의"),
    1518: ("policy", "n. 정책"),
    1519: ("regulation", "n. 규정"),
    1520: ("further", "ad. 게다가 a. 추가의"),
    1521: ("subsequent", "a. 추후의"),
    1522: ("thereafter", "ad. 그 후"),
    1523: ("shade", "n. 그늘, 응달"),
    1524: ("container", "n. 그릇, 컨테이너"),
    1525: ("miss", "v. 놓치다, 그리워하다"),
    1526: ("simply", "ad. 간단하게, 그저"),
    1527: ("extremely", "ad. 극단적으로"),
    1528: ("overcome", "v. 극복하다"),
    1529: ("dramatically", "ad. 극적으로"),
    1530: ("dramatic", "a. 극적인"),
    1531: ("minimally", "ad. 최소한으로"),
    1532: ("modernism", "n. 현대식"),
    1533: ("employee", "n. 종업원"),
    1534: ("serve as", "v. 종사하다"),
    1535: ("radically", "ad. 급진적으로"),
    1536: ("concern", "v. 걱정하다 n. 염려"),
    1537: ("eradicate", "v. 근절하다"),
    1538: ("monetary", "a. 금융의,재정의"),
    1539: ("forbid", "v. 금지하다"),
    1540: ("prohibit", "v. 금지하다"),
    1541: ("rapidly", "ad. 빠르게"),
    1542: ("courier", "n. 택배,택배원"),
    1543: ("paycheck", "n. 급여, 봉급"),
    1544: ("payroll", "n. 급여기록부"),
    1545: ("machinery", "n. 기계류"),
    1546: ("contributor", "n. 기부자"),
    1547: ("appliance", "n. 가전제품"),
    1548: ("await", "v. 기다리다,대기하다"),
    1549: ("anticipate", "v. 기대하다"),
    1550: ("record", "v. 기록하다 n. 기록"),
    1551: ("confidential", "a. 기밀의"),
    1552: ("elementary", "a. 기본의,초등의"),
    1553: ("contribution", "n. 기여"),
    1554: ("donation", "n. 기부"),
    1555: ("donate", "v. 기부하다"),
    1556: ("offend", "v. 기분상하게하다"),
    1557: ("meteorological", "a. 기상의,기상학의"),
    1558: ("prosecution", "n. 기소"),
    1559: ("prosecute", "v. 기소하다"),
    1560: ("technical", "a. 기술적인"),
    1561: ("contribute", "v. 기여하다"),
    1562: ("keynote", "n. 기조"),
    1563: ("existing", "a. 현존하는"),
    1564: ("found", "v. 설립하다"),
    1565: ("opportunity", "n. 기회"),
    1566: ("emergency", "n. 비상사태"),
    1567: ("urgent", "a. 긴급한"),
    1568: ("route", "n. 길"),
    1569: ("lengthen", "v. 길게하다, 늘이다"),
    1570: ("fragile", "a. 부서지기 쉬운"),
    1571: ("fit", "a. 딱 맞는 v. 맞추다"),
    1572: ("fasten", "v. 묶다"),
    1573: ("must-see", "n. 꼭보아야 할것"),
    1574: ("blossom", "n. 꽃,개화"),
    1575: ("procrastinate", "v. 끌다,지연하다"),
    1576: ("pull", "v. 끌다"),
    1577: ("attract", "v. 끌다"),
    1578: ("drawer", "n. 서랍"),
    1579: ("finalize", "v. 끝내다"),
    1580: ("terminate", "v. 끝내다"),
    1581: ("divide", "v. 나누다"),
    1582: ("remainder", "n. 나머지"),
    1583: ("branch", "n. 가지,지점"),
    1584: ("age", "n. 나이,시대"),
    1585: ("appear", "v. 나타나다,보이다"),
    1586: ("indicative", "a. 나타내는"),
    1587: ("indicate", "v. 지적하다"),
    1588: ("optimistic", "a. 낙천적인"),
    1589: ("deciduous", "a. 낙엽이 떨어지는"),
    1590: ("railing", "n. 난간"),
    1591: ("southern", "a. 남쪽의"),
    1592: ("matinee", "n. 낮공연 흥행"),
    1593: ("nap", "n. 낮잠"),
    1594: ("physician", "n. 내과의사"),
    1595: ("durable", "a. 내구성있는"),
    1596: ("pass out", "v. 나눠주다"),
    1597: ("overlook", "v. 내려다보다"),
    1598: ("disembark", "v. 내려오다"),
    1599: ("contents", "n. 내용물"),
    1600: ("unwillingness", "n. 내키지않음"),
    1601: ("widely", "ad. 널리"),
    1602: ("prevalent", "a. 만연한"),
    1603: ("widen", "v. 넓히다"),
    1604: ("broad", "a. 넓은, 광대한"),
    1605: ("broaden", "v. 넓히다,확장하다"),
    1606: ("expand", "v. 확장하다"),
    1607: ("labor", "n. 노동"),
    1608: ("union", "n. 조합"),
    1609: ("effort", "n. 노력"),
    1610: ("endeavor", "v. 노력하다"),
    1611: ("skilled", "a. 숙련된"),
    1612: ("exposure", "n. 노출"),
    1613: ("controversy", "n. 논란"),
    1614: ("argumentative", "a. 논쟁적인,따지기좋아하는"),
    1615: ("comment", "n. 논평"),
    1616: ("amazement", "n. 깜짝놀람"),
    1617: ("crop", "n. 수확"),
    1618: ("abate", "v. 약화시키다"),
    1619: ("press", "v. 누르다"),
    1620: ("prestige", "n. 명성"),
}
page_16 = {
    1621: ("ruler", "n. 통치자"),
    1622: ("prominently", "ad. 현저하게, 두드러지게"),
    1623: ("loose", "a. 풀린 ad. 느슨하게"),
    1624: ("streamline", "v. 간소화하다"),
    1625: ("efficient", "a. 효과적인"),
    1626: ("proficiency", "n. 능숙, 숙달"),
    1627: ("coming", "a. 다가오는"),
    1628: ("upcoming", "a. 다가오는"),
    1629: ("handle", "v. 다루다, 취급하다"),
    1630: ("differently", "ad. 다르게"),
    1631: ("differ", "v. 달라지다"),
    1632: ("different", "a. 다른"),
    1633: ("iron", "v. 다림질하다"),
    1634: ("somewhat", "ad. 어느정도, 약간"),
    1635: ("variety", "n. 다양성"),
    1636: ("diverse", "a. 다양한"),
    1637: ("diversified", "a. 다채로운"),
    1638: ("diversify", "v. 다양화하다"),
    1639: ("stage", "n. 무대"),
    1640: ("step", "n. 단계"),
    1641: ("escalate", "v. 단계적으로 확대시키다"),
    1642: ("deter", "v. 단념시키다"),
    1643: ("secure", "a. 안전한"),
    1644: ("tightly", "ad. 단단하게"),
    1645: ("simplify", "v. 간소화하다"),
    1646: ("insulation", "n. 단열"),
    1647: ("organization", "n. 조직"),
    1648: ("close", "v. 닫다 a. 가까운"),
    1649: ("console", "v. 위로하다"),
    1650: ("otherwise", "ad. 그렇지않으면"),
    1651: ("attain", "v. 도달하다"),
    1652: ("collateral", "a. 대등한, 평행한"),
    1653: ("party", "n. 당 (정당), 무리, 단체"),
    1654: ("bewildering", "a. 당혹케하는"),
    1655: ("waiting room", "n. 대합실"),
    1656: ("majority", "n. 과반수, 다수"),
    1657: ("metropolitan", "a. 대도시의"),
    1658: ("approximately", "ad. 대략"),
    1659: ("bulk", "n. 대량의 n. 부피"),
    1660: ("opposing", "a. 대항하는"),
    1661: ("loan", "n. 대출"),
    1662: ("largely", "ad. 대부분, 주로"),
    1663: ("embassy", "n. 대사관"),
    1664: ("alternative", "n. 대안 a. 대안의"),
    1665: ("contend", "v. 대결하다"),
    1666: ("replacement", "n. 대체, 후임자"),
    1667: ("delegation", "n. 대표단"),
    1668: ("delegate", "n. 대표자"),
    1669: ("representative", "n. 대표자, 직원"),
    1670: ("represent", "v. 대표하다"),
    1671: ("evacuate", "v. 피난시키다"),
    1672: ("toss", "v. 던지다"),
    1673: ("less", "a. 더 적은 ad. 더 적게"),
    1674: ("tool", "n. 도구"),
    1675: ("instrument", "n. 도구"),
    1676: ("drawing", "n. 도면"),
    1677: ("urban", "a. 도시의"),
    1678: ("introduction", "n. 도입"),
    1679: ("challenging", "a. 도전적인"),
    1680: ("arrival", "n. 도착"),
    1681: ("destination", "n. 도착지"),
    1682: ("arrive", "v. 도착하다"),
    1683: ("independent", "a. 독립적인"),
    1684: ("monopoly", "n. 독점"),
    1685: ("antitrust", "a. 독점을 반대하는"),
    1686: ("exclusively", "ad. 독점적으로"),
    1687: ("creativity", "n. 독창성"),
    1688: ("original", "a. 원래의"),
    1689: ("distinctively", "ad. 독특하게"),
    1690: ("unique", "a. 독특한"),
    1691: ("assist", "v. 돕다"),
    1692: ("motivate", "v. 동기부여하다"),
    1693: ("colleague", "n. 동료"),
    1694: ("alliance", "n. 동맹"),
    1695: ("enclose", "v. 동봉하다"),
    1696: ("simultaneously", "ad. 동시에"),
    1697: ("concurrently", "ad. 동시에"),
    1698: ("fluctuation", "n. 동요, 파동"),
    1699: ("agreement", "n. 동의, 합의"),
    1700: ("consent", "v. 동의하다"),
    1701: ("agree", "v. 동의하다"),
    1702: ("alumni", "n. 동창생"),
    1703: ("distinguished", "a. 눈에 띄는"),
    1704: ("belatedly", "ad. 뒤늦게"),
    1705: ("lag", "v. 뒤쳐지다"),
    1706: ("lift", "v. 들다"),
    1707: ("enter", "v. 들어가다"),
    1708: ("registration", "n. 등록"),
    1709: ("register", "v. 등록하다"),
    1710: ("enroll", "v. 등록하다"),
    1711: ("follow", "v. 따르다"),
    1712: ("occasionally", "ad. 때때로, 가끔"),
    1713: ("away", "ad. 떨어져서"),
    1714: ("detach", "v. 떼어내다"),
    1715: ("superb", "a. 뛰어난"),
    1716: ("band", "n. 띠 v. 단결하다"),
    1717: ("attractive", "a. 마음을 끄는"),
    1718: ("face", "v. 직면하다"),
    1719: ("friction", "n. 마찰"),
    1720: ("finally", "ad. 마침내"),
    1721: ("expire", "v. 만료되다"),
    1722: ("due", "a. 만기가 된"),
    1723: ("expiration", "n. 만기"),
    1724: ("chronic", "a. 만성의, 상습적인"),
    1725: ("unanimous", "a. 만장일치의"),
    1726: ("satisfaction", "n. 만족"),
    1727: ("satisfactory", "a. 만족한"),
    1728: ("satisfy", "v. 만족시키다"),
}
page_17 = {
    1729: ("sure", "a. 확실한"),
    1730: ("assert", "v. 확인한다"),
    1731: ("confirmation", "n. 확인"),
    1732: ("identify", "v. 확인하다"),
    1733: ("confirm", "v. 확인하다"),
    1734: ("expansion", "n. 확장"),
    1735: ("environmental", "a. 환경의"),
    1736: ("hospitality", "n. 환대"),
    1737: ("refund", "n. 환불 v. 환불하다"),
    1738: ("rebate", "n. 환불할인"),
    1739: ("reception", "n. 환영회"),
    1740: ("lively", "a. 활기찬"),
    1741: ("activity", "n. 활동"),
    1742: ("devastate", "v. 황폐화하다"),
    1743: ("audit", "n. 회계감사 v. 감사하다"),
    1744: ("accountant", "n. 회계사"),
    1745: ("fiscal", "a. 회계의"),
    1746: ("ledger", "n. 회계장부, 원장"),
    1747: ("memorandum", "n. 메모, 각서"),
    1748: ("recovery", "n. 회복"),
    1749: ("revitalize", "v. 회복시키다"),
    1750: ("corporation", "n. 회사, 법인"),
    1751: ("cooperate", "v. 협력하다"),
    1752: ("convention", "n. 회의"),
    1753: ("conference", "n. 회의"),
    1754: ("carrousel", "n. 회전목마"),
    1755: ("effective", "a. 효과적인"),
    1756: ("efficiency", "n. 능률, 효율"),
    1757: ("effectiveness", "n. 효과적임"),
    1758: ("efficiently", "ad. 능률적으로"),
    1759: ("patronize", "v. 후원하다"),
    1760: ("recession", "n. 후퇴, 경기침체"),
    1761: ("creditable", "a. 훌륭한"),
    1762: ("stir", "v. 휘젓다 n. 각성"),
    1763: ("leave", "n. 휴가 v. 퇴근하다"),
    1764: ("rest", "n. 휴식 v. 쉬다"),
    1765: ("break", "n. 휴식"),
    1766: ("adjourn", "v. 휴정하다"),
    1767: ("scatter", "v. 흩뿌리다"),
    1768: ("overflow", "v. 흘러 넘치다"),
    1769: ("blemish", "n. 흠, 오점"),
    1770: ("inhalation", "n. 흡입"),
    1771: ("tear down", "v. 허물다, 해체하다"),
    1772: ("go through", "v. 살펴보다, 통과되다"),
    1773: ("infringe on", "v. 침해하다"),
    1774: ("withdraw from", "v. 철수하다"),
    1775: ("drop off", "v. 맡기다"),
    1776: ("abide by", "v. 준수하다"),
    1777: ("pick up", "v. 가져가다"),
    1778: ("impose tax on imported goods", "v. 수입품에 관세를 부과하다"),
    1779: ("up to", "~까지"),
    1780: ("in one's place", "~대신에"),
    1781: ("due to", "~때문에"),
    1782: ("on account of", "~때문에"),
    1783: ("in terms of", "~면에서"),
    1784: ("be made of", "~로 구성되다"),
    1785: ("judging from", "~으로 판단하건데"),
    1786: ("be noted for", "~으로 유명하다"),
    1787: ("be known for", "~으로 유명하다"),
    1788: ("owing to", "~때문에"),
    1789: ("be bound for", "지명 ~로 향하는"),
    1790: ("collect from", "~로부터 모으다"),
    1791: ("subscribe to", "구독하다"),
    1792: ("look forward to -ing", "기대하다"),
    1793: ("on behalf of", "A를 대표하여"),
    1794: ("add to", "~에 더하다"),
    1795: ("call on 사람", "방문하다"),
    1796: ("lead to", "초래하다"),
    1797: ("cope with", "대처하다"),
    1798: ("deal with", "다루다"),
    1799: ("be acquainted with", "알다"),
    1800: ("rule out", "배제하다"),
    1801: ("the trend toward", "~적 경향"),
    1802: ("ahead of", "앞서"),
    1803: ("do without", "없이 지내다"),
    1804: ("be appreciative of", "감사하다"),
    1805: ("inflict on", "타격을 주다"),
    1806: ("be interested in", "흥미가 있는"),
    1807: ("as for", "~에 관해 말하자면"),
    1808: ("as to", "~에 관해"),
    1809: ("in regard to", "~에 관해"),
    1810: ("in reference to", "~에 관해"),
    1811: ("lean against", "기대다"),
    1812: ("contribute to", "기여하다"),
    1813: ("attribute to", "~의 탓으로 돌리다"),
    1814: ("expose to", "노출하다"),
    1815: ("I was taken by surprise", "당황했다"),
    1816: ("be skilled in-ing", "능숙하다"),
    1817: ("be late for", "늦은"),
    1818: ("emphasis on", "강조하다"),
    1819: ("contribution to", "부담금, 기여금"),
    1820: ("satisfaction with", "~에 대한 만족"),
    1821: ("tax on 명사", "~에 대한 세금"),
    1822: ("commitment to", "~에 대한 헌신"),
    1823: ("be concerned about", "걱정하다"),
    1824: ("be worried about", "걱정하다"),
    1825: ("refer to", "언급하다"),
    1826: ("be familiar with", "익숙한"),
    1827: ("be liable for", "의무가 있는"),
    1828: ("be responsible for", "책임이 있는"),
    1829: ("dedicate oneself to", "전념하다"),
    1830: ("with regard to", "~에 관해"),
    1831: ("spend money on", "돈을 쓰다"),
    1832: ("agree on 안건", "동의하다"),
    1833: ("stop by 장소", "들르다"),
    1834: ("come by 장소", "들르다"),
}
page_18 = {
1835: ("drop by", "들르다"),
1836: ("sign up for", "신청하다"),
1837: ("according to", "~에 따르면"),
1838: ("in accordance with", "~에 따라서"),
1839: ("follow up on", "~을 끝까지 하다"),
1840: ("be satisfied with", "만족하다"),
1841: ("fit in", "시간을 내다"),
1842: ("adjust to", "적응하다"),
1843: ("be absorbed in", "몰두하다"),
1844: ("object to", "반대하다"),
1845: ("be disappointed with", "실망하다"),
1846: ("be involved in", "연루되다"),
1847: ("be subject to", "~의 대상이다"),
1848: ("have an impact on", "영향을 주다"),
1849: ("prior to", "~에 앞서"),
1850: ("in response to", "응답하여"),
1851: ("be accustomed to -ing", "익숙하다"),
1852: ("be admitted to", "승인되다"),
1853: ("apply to", "적용되다"),
1854: ("be engaged in", "종사하다"),
1855: ("concentrate on", "집중하다"),
1856: ("participate in", "참가하다"),
1857: ("take part in", "참가하다"),
1858: ("be based on", "근거를 두다"),
1859: ("invest in", "투자하다"),
1860: ("despite", "~에도 불구하고"),
1861: ("in spite of", "~에도 불구하고"),
1862: ("as of today", "오늘날짜로"),
1863: ("do business with", "거래하다"),
1864: ("be associated with", "관련되다"),
1865: ("indulged in", "~에 빠진"),
1866: ("differ from", "~와 다르다"),
1867: ("be different from", "~와 다른"),
1868: ("contrary to", "~에 반해"),
1869: ("agree with 사람", "동의하다"),
1870: ("in comparison with", "~와 견주어 볼때"),
1871: ("be engaged to", "~와 약혼한"),
1872: ("be done with", "끝장내다"),
1873: ("get in touch with", "연락하다"),
1874: ("get along with", "어울리다"),
1875: ("be far from", "멀다"),
1876: ("in addition to", "게다가"),
1877: ("upon request", "요청한대로"),
1878: ("decide on", "결정하다"),
1879: ("escalate into", "악화되다"),
1880: ("be limited to", "제한되다"),
1881: ("keep track of", "추적하다"),
1882: ("plan on -ing", "~할 계획이다"),
1883: ("on behalf of", "대신에"),
1884: ("commit oneself to", "헌신하다"),
1885: ("make up for", "보상하다"),
1886: ("approve of", "승인하다"),
1887: ("supply for", "공급하다"),
1888: ("put in for", "요청하다"),
1889: ("be desirous of", "탐내다"),
1890: ("ask for", "요청하다"),
1891: ("request for", "요청하다"),
1892: ("be in intend for", "모두를 위한 것"),
1893: ("stare at", "응시하다"),
1894: ("take advantage of", "이용하다"),
1895: ("except for", "제외하고"),
1896: ("with the exception of", "제외하고"),
1897: ("hand in", "제출하다"),
1898: ("turn in", "반납하다"),
1899: ("in the event of", "~의 경우"),
1900: ("in case of", "~의 경우"),
1901: ("stand in for", "일을 대신하다"),
1902: ("fail in", "실패하다"),
1903: ("at the rate(cost) of", "~의 비율로"),
1904: ("in front of", "~의 앞에"),
1905: ("in the suburbs of", "근교에"),
1906: ("run a risk of", "위험을 무릅쓰다"),
1907: ("be courtesy of", "호의로"),
1908: ("run out of", "떨어지다"),
1909: ("retire from", "은퇴하다"),
1910: ("be in charge of", "책임지다"),
1911: ("be apt to", "~하는 경향이 있다"),
1912: ("be liable to", "~하는 경향이 있다"),
1913: ("be likely to", "~하는 경향이 있다"),
1914: ("tend to", "~하는 경향이 있다"),
1915: ("have a hard time -ing", "힘든 시간을 보내다"),
1916: ("be suspected of", "혐의를 받다"),
1917: ("be capable of", "할 수 있다"),
1918: ("be eligible for", "자격이 있다"),
1919: ("be eligible to", "자격이 있다"),
1920: ("be entitled to", "자격이 있다"),
1921: ("be qualified for", "자격이 있다"),
1922: ("be supposed to", "~할 예정이다"),
1923: ("bound for", "~행의"),
1924: ("rise by 20%", "20% 만큼 오르다"),
1925: ("come in 3rd", "3등으로 들어오다"),
1926: ("accuse A of B", "A를 B로 고소하다"),
1927: ("present A with B", "주다"),
1928: ("prevent from -ing", "막다"),
1929: ("remind A of B", "떠올리다"),
1930: ("take A for B", "A를 B로 여기다"),
1931: ("familiarize A with B", "친숙하게 지내다"),
1932: ("leave A out", "빼다, 무시하다"),
1933: ("take A into effect", "실행하다"),
1934: ("cut down on A", "줄이다"),
1935: ("provide A with B", "제공하다"),
1936: ("provide B for A", "제공하다"),
1937: ("attribute A to B", "~의 탓으로 돌리다"),
1938: ("protect A from B", "보호하다"),
1939: ("substitute A for B", "대체하다"),
1940: ("replace B with A", "대체하다"),
}
page_19 = {
1941: ("operate within the guidelines", "지침내에서 운영하다"),
1942: ("pay off", "성과를 내다"),
1943: ("hand over", "건네다"),
1944: ("look over", "검토하다"),
1945: ("take a shot", "시도해보다"),
1946: ("in conclusion", "결론적으로"),
1947: ("reach a decision", "결정을 내리다"),
1948: ("see about", "고려하다"),
1949: ("in common", "공동으로"),
1950: ("show off", "과시하다"),
1951: ("place an ad", "광고하다"),
1952: ("take turns", "교대하다"),
1953: ("give in", "굴복하다"),
1954: ("scrape off", "벗겨내다"),
1955: ("be willing to", "기꺼이 ~하다"),
1956: ("on board", "탑승한"),
1957: ("be taken by surprise", "의외로 놀라다"),
1958: ("slip one's mind", "깜빡잊다"),
1959: ("take out", "대접하다"),
1960: ("turn off", "끄다"),
1961: ("show up", "나타나다"),
1962: ("stand for", "지지하다"),
1963: ("put down", "착륙하다"),
1964: ("get off", "이륙하다"),
1965: ("lay down", "사임하다"),
1966: ("at a surprisingly fast pace", "놀랍게 빠른 속도로"),
1967: ("with high unemployment rates", "높은 실업률로 인해"),
1968: ("in one's absence", "부재중에"),
1969: ("line up", "정렬"),
1970: ("at the latest", "늦어도"),
1971: ("come up", "떠오르다"),
1972: ("in bulk", "대량으로"),
1973: ("into the next century", "다음세기에"),
1974: ("wipe off", "씻어내다"),
1975: ("step down", "퇴진하다"),
1976: ("stick to", "고수하다"),
1977: ("for the time being", "당분간"),
1978: ("for the present", "현재로서는"),
1979: ("take for granted", "당연히 여기다"),
1980: ("instead of", "대신에"),
1981: ("give a hand", "도와주다"),
1982: ("along the way", "길 따라"),
1983: ("take care of", "돌보다"),
1984: ("at once", "즉시"),
1985: ("at the same time", "동시에"),
1986: ("come up with", "(생각이) 떠오르다"),
1987: ("comply with", "준수하다"),
1988: ("workout", "운동"),
1989: ("take on", "떠맡다"),
1990: ("hold off", "보류하다"),
1991: ("a lot of", "많은"),
1992: ("the number of", "수"),
1993: ("a number of", "많은"),
1994: ("out of business", "폐업한"),
1995: ("take over", "인수하다"),
1996: ("sold out", "매진된"),
1997: ("in the corner", "궁지에 몰린"),
1998: ("take a bath", "목욕하다"),
1999: ("in person", "직접"),
2000: ("for free", "공짜로"),
2001: ("at random", "무작위로"),
2002: ("draw up", "구상하다"),
2003: ("be in the market for", "~구입에 관심이 있는"),
2004: ("ahead of time", "미리"),
2005: ("in advance", "미리"),
2006: ("give a big hand", "큰 도움을 주다"),
2007: ("be bound to", "의무가 있다"),
2008: ("in print", "출판되는"),
2009: ("put in the mail", "우편으로 보내다"),
2010: ("set the table", "밥상을 차리다"),
2011: ("out of recession", "불경기에서 벗어난"),
2012: ("make up for", "보상하다"),
2013: ("under warranty", "보증기간중인"),
2014: ("compensate for", "보상하다"),
2015: ("out of town", "출장중인"),
2016: ("in recession", "불경기인"),
2017: ("compare with", "비교하다"),
2018: ("in service", "복무중인"),
2019: ("in use", "사용중인"),
2020: ("out of service", "고장난, 퇴직한"),
2021: ("work out", "운동하다"),
2022: ("in writing", "서면으로"),
2023: ("sign out", "서명하다"),
2024: ("account for", "설명하다"),
2025: ("set up", "설치하다"),
2026: ("a survey on customer preference", "고객 선호조사"),
2027: ("be taken into custody", "구금되다"),
2028: ("check in", "탑승,투숙을 하다"),
2029: ("out of breath", "숨 가쁜"),
2030: ("get a car started", "운전하다"),
2031: ("attend on", "병 간호하다"),
2032: ("fall through", "빠지다, 실패하다"),
2033: ("what a nuisance", "성가시구나!"),
2034: ("close by", "인근에서"),
2035: ("have yet to do", "아직 ~하지 않았다"),
2036: ("outdoors", "야외에서"),
2037: ("at all times", "항상"),
2038: ("come by", "잠깐 들르다"),
2039: ("lock oneself out", "키를 차에 두고 잠그다"),
2040: ("next to", "옆에"),
2041: ("confirm a reservation", "예약을 확인하다"),
2042: ("to the fullest", "최대한으로"),
2043: ("let up", "느슨해지다"),
2044: ("in the mail", "배달중에"),
2045: ("by mail", "우편으로"),
2046: ("fare worse", "더 나빠지다"),
2047: ("fare well", "작별, 송별회"),
2048: ("at the end of the month", "이달 말에"),
}
page_20 = {
    2049: ("Monday through Friday", "월요일부터 금요일까지"),
    2050: ("at stake", "위태로운"),
    2051: ("at the risk of", "위험을 무릅쓰고"),
    2052: ("attend to", "시중들다"),
    2053: ("be in effect", "시행되다"),
    2054: ("open an account", "계좌를 개설하다"),
    2055: ("turn down", "거절하다"),
    2056: ("be suspicious of", "의심하다"),
    2057: ("depend on", "의지하다"),
    2058: ("rely on", "의지하다"),
    2059: ("count on", "의지하다"),
    2060: ("take off", "이륙하다, 출발하다"),
    2061: ("move around", "돌아다니다"),
    2062: ("draw on", "의지하다"),
    2063: ("figure out", "이해하다"),
    2064: ("make out", "이해하다"),
    2065: ("put on", "입다"),
    2066: ("try on", "입어보다"),
    2067: ("hold back", "보류하다"),
    2068: ("work on", "착수하다"),
    2069: ("chop up", "잘게 썰다"),
    2070: ("drop in", "잠깐 들르다"),
    2071: ("out of stock", "품절인"),
    2072: ("in stock", "재고가 있는"),
    2073: ("in the red", "적자 상태인"),
    2074: ("in the black", "흑자인"),
    2075: ("in the end", "결국에"),
    2076: ("through out the world", "전세계에"),
    2077: ("do one's utmost/best", "최선을 다하다"),
    2078: ("on the phone", "통화중인"),
    2079: ("hang up", "전화를끊다"),
    2080: ("hold the line", "전화를끊지않고 기다리다"),
    2081: ("give a ring", "전화 걸다"),
    2082: ("out of print", "절판된"),
    2083: ("deprive A of B", "빼앗다"),
    2084: ("with care", "주의깊게"),
    2085: ("tune up", "조율하다"),
    2086: ("subordinate to", "종속하는"),
    2087: ("fill an order", "주문에 응하다"),
    2088: ("place an order", "주문하다"),
    2089: ("wait in line", "줄서서 기다리다"),
    2090: ("cut short", "삭감하다"),
    2091: ("in rows", "일렬로"),
    2092: ("right away", "당장"),
    2093: ("be about to", "막~하려하다"),
    2094: ("be slightly delayed", "다소 지연된"),
    2095: ("stand by", "대기하다"),
    2096: ("keep to", "지키다"),
    2097: ("drag on", "질질 끌다"),
    2098: ("run after", "뒤쫓다"),
    2099: ("set out", "준비, 출발"),
    2100: ("search for", "찾다"),
    2101: ("stay tuned", "채널고정"),
    2102: ("fill out/in", "기입하다"),
    2103: ("leaf through", "대충 훑어보다"),
    2104: ("at first", "처음에는"),
    2105: ("check out", "계산대"),
    2106: ("at its peak/best", "절정인"),
    2107: ("at least", "최소한"),
    2108: ("start out", "시작하다"),
    2109: ("call off", "취소하다"),
    2110: ("put away", "치우다"),
    2111: ("take away", "치우다"),
    2112: ("hold up", "정지"),
    2113: ("make the bed", "이불을 개다"),
    2114: ("turn on", "켜다"),
    2115: ("get in/on", "타다"),
    2116: ("reach into", "이르다, 도달하다"),
    2117: ("give up", "포기하다"),
    2118: ("out of order", "고장난"),
    2119: ("plug in", "연결하다"),
    2120: ("head off", "막다, 저지하다"),
    2121: ("take a day off", "휴가내다"),
    2122: ("in a row", "일렬로"),
    2123: ("at a reduced price", "할인된 가격으로"),
    2124: ("get through", "통과하다"),
    2125: ("lay off", "해고"),
    2126: ("capitalize on", "이용하다"),
    2127: ("be curious about", "호기심을 가지다"),
    2128: ("for oneself", "스스로"),
    2129: ("on one's own", "스스로"),
    2130: ("make sure", "확인하다"),
    2131: ("at the meeting", "회의에서"),
    2132: ("go into effect", "효력이 발생하다"),
    2133: ("on vacation", "휴가중인"),
    2134: ("take a break", "휴식을 취하다"),
    2135: ("glance at", "흘깃 보다"),
    2136: ("above all", "무엇보다도"),
    2137: ("depending on", "~에 따라서"),
    2138: ("full-scale", "본격적인"),
    2139: ("array of", "다양한"),
    2140: ("credit history", "신용기록"),
    2141: ("refinancing", "재융자"),
    2142: ("evolving", "발달하는"),
    2143: ("by the time", "~할때쯤"),
    2144: ("after use", "사용후에"),
    2145: ("evenly", "고르게"),
    2146: ("those who", "~하는 사람들"),
    2147: ("anyone who", "~하는 사람들"),
    2148: ("operating expenses", "운영비"),
    2149: ("in~ing", "~함에 있어서"),
    2150: ("monitor", "감시하다"),
}

word_data = {
    "page_1": page_1, "page_2": page_2, "page_3": page_3, "page_4": page_4, "page_5": page_5, 
    "page_6": page_6, "page_7": page_7, "page_8": page_8, "page_9": page_9, "page_10": page_10,
    "page_11": page_11, "page_12": page_12, "page_13": page_13, "page_14": page_14, "page_15": page_15,
    "page_16": page_16, "page_17": page_17, "page_18": page_18, "page_19": page_19, "page_20": page_20
}
